//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: athletics.proto
// Note: requires additional types generated from: battle.proto
namespace athletics
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsMatchDefendRequest")]
  public partial class AthleticsMatchDefendRequest : global::ProtoBuf.IExtensible
  {
    public AthleticsMatchDefendRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DefendInfo")]
  public partial class DefendInfo : global::ProtoBuf.IExtensible
  {
    public DefendInfo() {}
    
    private int _ranking = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private int _defuid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"defuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int defuid
    {
      get { return _defuid; }
      set { _defuid = value; }
    }
    private int _headid = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headid
    {
      get { return _headid; }
      set { _headid = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _fighting_power = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fighting_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fighting_power
    {
      get { return _fighting_power; }
      set { _fighting_power = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsMatchDefendResponse")]
  public partial class AthleticsMatchDefendResponse : global::ProtoBuf.IExtensible
  {
    public AthleticsMatchDefendResponse() {}
    
    private int _current_ranking = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"current_ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current_ranking
    {
      get { return _current_ranking; }
      set { _current_ranking = value; }
    }
    private int _highest_ranking = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"highest_ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int highest_ranking
    {
      get { return _highest_ranking; }
      set { _highest_ranking = value; }
    }
    private int _cd_time = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cd_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cd_time
    {
      get { return _cd_time; }
      set { _cd_time = value; }
    }
    private readonly global::System.Collections.Generic.List<athletics.DefendInfo> _defend = new global::System.Collections.Generic.List<athletics.DefendInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"defend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<athletics.DefendInfo> defend
    {
      get { return _defend; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsBuyTimesRequest")]
  public partial class AthleticsBuyTimesRequest : global::ProtoBuf.IExtensible
  {
    public AthleticsBuyTimesRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsBuyTimesResponse")]
  public partial class AthleticsBuyTimesResponse : global::ProtoBuf.IExtensible
  {
    public AthleticsBuyTimesResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsBuyCDRequest")]
  public partial class AthleticsBuyCDRequest : global::ProtoBuf.IExtensible
  {
    public AthleticsBuyCDRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsBuyCDResponse")]
  public partial class AthleticsBuyCDResponse : global::ProtoBuf.IExtensible
  {
    public AthleticsBuyCDResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsViewDefendRequest")]
  public partial class AthleticsViewDefendRequest : global::ProtoBuf.IExtensible
  {
    public AthleticsViewDefendRequest() {}
    
    private int _ranking;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsViewDefendResponse")]
  public partial class AthleticsViewDefendResponse : global::ProtoBuf.IExtensible
  {
    public AthleticsViewDefendResponse() {}
    
    private int _ranking;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private int _defuid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"defuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int defuid
    {
      get { return _defuid; }
      set { _defuid = value; }
    }
    private battle.DefInfoResponse _def_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"def_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public battle.DefInfoResponse def_info
    {
      get { return _def_info; }
      set { _def_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsBeginChallengeRequest")]
  public partial class AthleticsBeginChallengeRequest : global::ProtoBuf.IExtensible
  {
    public AthleticsBeginChallengeRequest() {}
    
    private int _ranking;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _soldiers = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"soldiers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> soldiers
    {
      get { return _soldiers; }
    }
  
    private int _captainid = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"captainid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int captainid
    {
      get { return _captainid; }
      set { _captainid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsBeginChallengeResponse")]
  public partial class AthleticsBeginChallengeResponse : global::ProtoBuf.IExtensible
  {
    public AthleticsBeginChallengeResponse() {}
    
    private int _ranking;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsRecordRequest")]
  public partial class AthleticsRecordRequest : global::ProtoBuf.IExtensible
  {
    public AthleticsRecordRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsRecordResponse")]
  public partial class AthleticsRecordResponse : global::ProtoBuf.IExtensible
  {
    public AthleticsRecordResponse() {}
    
    private readonly global::System.Collections.Generic.List<athletics.AthleticsRecordResponse.RecordInfo> _record_info = new global::System.Collections.Generic.List<athletics.AthleticsRecordResponse.RecordInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"record_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<athletics.AthleticsRecordResponse.RecordInfo> record_info
    {
      get { return _record_info; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecordInfo")]
  public partial class RecordInfo : global::ProtoBuf.IExtensible
  {
    public RecordInfo() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _ranking_change = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ranking_change", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ranking_change
    {
      get { return _ranking_change; }
      set { _ranking_change = value; }
    }
    private int _headid = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headid
    {
      get { return _headid; }
      set { _headid = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _challenge_time = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"challenge_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int challenge_time
    {
      get { return _challenge_time; }
      set { _challenge_time = value; }
    }
    private int _flag = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private int _challenge_type = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"challenge_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int challenge_type
    {
      get { return _challenge_type; }
      set { _challenge_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsSetRecordFlagRequest")]
  public partial class AthleticsSetRecordFlagRequest : global::ProtoBuf.IExtensible
  {
    public AthleticsSetRecordFlagRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsSetRecordFlagResponse")]
  public partial class AthleticsSetRecordFlagResponse : global::ProtoBuf.IExtensible
  {
    public AthleticsSetRecordFlagResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsSettleRequest")]
  public partial class AthleticsSettleRequest : global::ProtoBuf.IExtensible
  {
    public AthleticsSettleRequest() {}
    
    private int _ranking;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private int _defuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"defuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defuid
    {
      get { return _defuid; }
      set { _defuid = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _destory_builds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"destory_builds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> destory_builds
    {
      get { return _destory_builds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _die_soldiers = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"die_soldiers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> die_soldiers
    {
      get { return _die_soldiers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StageSoldierSettle")]
  public partial class StageSoldierSettle : global::ProtoBuf.IExtensible
  {
    public StageSoldierSettle() {}
    
    private int _soldierid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"soldierid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int soldierid
    {
      get { return _soldierid; }
      set { _soldierid = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsSettleResponse")]
  public partial class AthleticsSettleResponse : global::ProtoBuf.IExtensible
  {
    public AthleticsSettleResponse() {}
    
    private int _star = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private int _reward = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private battle.SettleResourse _resource = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public battle.SettleResourse resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private readonly global::System.Collections.Generic.List<athletics.StageSoldierSettle> _soldierinfos = new global::System.Collections.Generic.List<athletics.StageSoldierSettle>();
    [global::ProtoBuf.ProtoMember(4, Name=@"soldierinfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<athletics.StageSoldierSettle> soldierinfos
    {
      get { return _soldierinfos; }
    }
  
    private bool _win = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool win
    {
      get { return _win; }
      set { _win = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MakeAthleticsRankingRequest")]
  public partial class MakeAthleticsRankingRequest : global::ProtoBuf.IExtensible
  {
    public MakeAthleticsRankingRequest() {}
    
    private int _ranking;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MakeAthleticsRankingResponse")]
  public partial class MakeAthleticsRankingResponse : global::ProtoBuf.IExtensible
  {
    public MakeAthleticsRankingResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsIsFightingRequest")]
  public partial class AthleticsIsFightingRequest : global::ProtoBuf.IExtensible
  {
    public AthleticsIsFightingRequest() {}
    
    private int _ranking;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private int _defuid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"defuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int defuid
    {
      get { return _defuid; }
      set { _defuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsIsFightingResponse")]
  public partial class AthleticsIsFightingResponse : global::ProtoBuf.IExtensible
  {
    public AthleticsIsFightingResponse() {}
    
    private readonly global::System.Collections.Generic.List<athletics.AthleticsIsFightingResponse.ChangeDefendInfo> _changedefend = new global::System.Collections.Generic.List<athletics.AthleticsIsFightingResponse.ChangeDefendInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"changedefend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<athletics.AthleticsIsFightingResponse.ChangeDefendInfo> changedefend
    {
      get { return _changedefend; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeDefendInfo")]
  public partial class ChangeDefendInfo : global::ProtoBuf.IExtensible
  {
    public ChangeDefendInfo() {}
    
    private athletics.DefendInfo _defend = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"defend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public athletics.DefendInfo defend
    {
      get { return _defend; }
      set { _defend = value; }
    }
    private battle.DefInfoResponse _def_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"def_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public battle.DefInfoResponse def_info
    {
      get { return _def_info; }
      set { _def_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AthleticsRankingResponse")]
  public partial class AthleticsRankingResponse : global::ProtoBuf.IExtensible
  {
    public AthleticsRankingResponse() {}
    
    private int _ranking;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}