//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: battle.proto
// Note: requires additional types generated from: captain.proto
namespace battle
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DefInfoRequest")]
  public partial class DefInfoRequest : global::ProtoBuf.IExtensible
  {
    public DefInfoRequest() {}
    
    private int _def_uid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"def_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int def_uid
    {
      get { return _def_uid; }
      set { _def_uid = value; }
    }
    private int _canvas_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"canvas_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int canvas_id
    {
      get { return _canvas_id; }
      set { _canvas_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierInfo")]
  public partial class SoldierInfo : global::ProtoBuf.IExtensible
  {
    public SoldierInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _soldiertypeid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"soldiertypeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int soldiertypeid
    {
      get { return _soldiertypeid; }
      set { _soldiertypeid = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _starlevel = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"starlevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int starlevel
    {
      get { return _starlevel; }
      set { _starlevel = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _quality = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _askill_level = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"askill_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int askill_level
    {
      get { return _askill_level; }
      set { _askill_level = value; }
    }
    private int _skill1_level = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"skill1_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill1_level
    {
      get { return _skill1_level; }
      set { _skill1_level = value; }
    }
    private int _skill2_level = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"skill2_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill2_level
    {
      get { return _skill2_level; }
      set { _skill2_level = value; }
    }
    private int _skill3_level = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"skill3_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill3_level
    {
      get { return _skill3_level; }
      set { _skill3_level = value; }
    }
    private int _skill4_level = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"skill4_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill4_level
    {
      get { return _skill4_level; }
      set { _skill4_level = value; }
    }
    private int _skill5_level = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"skill5_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill5_level
    {
      get { return _skill5_level; }
      set { _skill5_level = value; }
    }
    private int _cx = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cx
    {
      get { return _cx; }
      set { _cx = value; }
    }
    private int _cy = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cy
    {
      get { return _cy; }
      set { _cy = value; }
    }
    private int _equipment0 = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"equipment0", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipment0
    {
      get { return _equipment0; }
      set { _equipment0 = value; }
    }
    private int _equipment1 = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"equipment1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipment1
    {
      get { return _equipment1; }
      set { _equipment1 = value; }
    }
    private int _equipment2 = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"equipment2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipment2
    {
      get { return _equipment2; }
      set { _equipment2 = value; }
    }
    private int _equipment3 = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"equipment3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipment3
    {
      get { return _equipment3; }
      set { _equipment3 = value; }
    }
    private int _equipment4 = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"equipment4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipment4
    {
      get { return _equipment4; }
      set { _equipment4 = value; }
    }
    private int _equipment5 = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"equipment5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipment5
    {
      get { return _equipment5; }
      set { _equipment5 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipBuildInfo")]
  public partial class ShipBuildInfo : global::ProtoBuf.IExtensible
  {
    public ShipBuildInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _objid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"objid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int objid
    {
      get { return _objid; }
      set { _objid = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _quality = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private int _starlevel = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"starlevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int starlevel
    {
      get { return _starlevel; }
      set { _starlevel = value; }
    }
    private int _buildtype = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"buildtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buildtype
    {
      get { return _buildtype; }
      set { _buildtype = value; }
    }
    private int _cx = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cx
    {
      get { return _cx; }
      set { _cx = value; }
    }
    private int _cy = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cy
    {
      get { return _cy; }
      set { _cy = value; }
    }
    private int _shipput_data0 = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"shipput_data0", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int shipput_data0
    {
      get { return _shipput_data0; }
      set { _shipput_data0 = value; }
    }
    private int _shipput_data1 = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"shipput_data1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int shipput_data1
    {
      get { return _shipput_data1; }
      set { _shipput_data1 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _coin = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _wood = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"wood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int wood
    {
      get { return _wood; }
      set { _wood = value; }
    }
    private string _servername = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"servername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string servername
    {
      get { return _servername; }
      set { _servername = value; }
    }
    private string _servernode = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"servernode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string servernode
    {
      get { return _servernode; }
      set { _servernode = value; }
    }
    private int _uid = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceInfo")]
  public partial class ResourceInfo : global::ProtoBuf.IExtensible
  {
    public ResourceInfo() {}
    
    private int _wood = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"wood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int wood
    {
      get { return _wood; }
      set { _wood = value; }
    }
    private int _coin = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DefInfoResponse")]
  public partial class DefInfoResponse : global::ProtoBuf.IExtensible
  {
    public DefInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<battle.SoldierInfo> _soldier_info = new global::System.Collections.Generic.List<battle.SoldierInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"soldier_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<battle.SoldierInfo> soldier_info
    {
      get { return _soldier_info; }
    }
  
    private readonly global::System.Collections.Generic.List<battle.ShipBuildInfo> _shipput_info = new global::System.Collections.Generic.List<battle.ShipBuildInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"shipput_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<battle.ShipBuildInfo> shipput_info
    {
      get { return _shipput_info; }
    }
  
    private int _deck_level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deck_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int deck_level
    {
      get { return _deck_level; }
      set { _deck_level = value; }
    }
    private battle.UserInfo _user_info = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"user_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public battle.UserInfo user_info
    {
      get { return _user_info; }
      set { _user_info = value; }
    }
    private battle.ResourceInfo _resource_info = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"resource_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public battle.ResourceInfo resource_info
    {
      get { return _resource_info; }
      set { _resource_info = value; }
    }
    private string _map = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string map
    {
      get { return _map; }
      set { _map = value; }
    }
    private string _shape = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"shape", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string shape
    {
      get { return _shape; }
      set { _shape = value; }
    }
    private int _width = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }
    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
    private int _canvas_id = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"canvas_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int canvas_id
    {
      get { return _canvas_id; }
      set { _canvas_id = value; }
    }
    private captain.CaptainInfoResponse _captain_infos = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"captain_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public captain.CaptainInfoResponse captain_infos
    {
      get { return _captain_infos; }
      set { _captain_infos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankInfoRequest")]
  public partial class RankInfoRequest : global::ProtoBuf.IExtensible
  {
    public RankInfoRequest() {}
    
    private int _from = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int from
    {
      get { return _from; }
      set { _from = value; }
    }
    private int _to = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int to
    {
      get { return _to; }
      set { _to = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankInfo")]
  public partial class RankInfo : global::ProtoBuf.IExtensible
  {
    public RankInfo() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _attack_win = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"attack_win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attack_win
    {
      get { return _attack_win; }
      set { _attack_win = value; }
    }
    private int _defend_win = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"defend_win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int defend_win
    {
      get { return _defend_win; }
      set { _defend_win = value; }
    }
    private int _reward = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private int _uid = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _rank = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private int _canvasid = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"canvasid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int canvasid
    {
      get { return _canvasid; }
      set { _canvasid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankInfoResponse")]
  public partial class RankInfoResponse : global::ProtoBuf.IExtensible
  {
    public RankInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<battle.RankInfo> _rank_info = new global::System.Collections.Generic.List<battle.RankInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rank_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<battle.RankInfo> rank_info
    {
      get { return _rank_info; }
    }
  
    private battle.RankInfo _self_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"self_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public battle.RankInfo self_info
    {
      get { return _self_info; }
      set { _self_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchRequest")]
  public partial class SearchRequest : global::ProtoBuf.IExtensible
  {
    public SearchRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchResponse")]
  public partial class SearchResponse : global::ProtoBuf.IExtensible
  {
    public SearchResponse() {}
    
    private int _defuid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"defuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int defuid
    {
      get { return _defuid; }
      set { _defuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SettleResourse")]
  public partial class SettleResourse : global::ProtoBuf.IExtensible
  {
    public SettleResourse() {}
    
    private int _coin = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _wood = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"wood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int wood
    {
      get { return _wood; }
      set { _wood = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SettleRequest")]
  public partial class SettleRequest : global::ProtoBuf.IExtensible
  {
    public SettleRequest() {}
    
    private int _defuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"defuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defuid
    {
      get { return _defuid; }
      set { _defuid = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _destory_builds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"destory_builds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> destory_builds
    {
      get { return _destory_builds; }
    }
  
    private readonly global::System.Collections.Generic.List<battle.SettleRequest.DieSoldiers> _die_soldiers = new global::System.Collections.Generic.List<battle.SettleRequest.DieSoldiers>();
    [global::ProtoBuf.ProtoMember(3, Name=@"die_soldiers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<battle.SettleRequest.DieSoldiers> die_soldiers
    {
      get { return _die_soldiers; }
    }
  
    private int _battlemode = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"battlemode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battlemode
    {
      get { return _battlemode; }
      set { _battlemode = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DieSoldiers")]
  public partial class DieSoldiers : global::ProtoBuf.IExtensible
  {
    public DieSoldiers() {}
    
    private int _soldierid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"soldierid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int soldierid
    {
      get { return _soldierid; }
      set { _soldierid = value; }
    }
    private int _cx;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cx
    {
      get { return _cx; }
      set { _cx = value; }
    }
    private int _cy;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cy
    {
      get { return _cy; }
      set { _cy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SettleResponse")]
  public partial class SettleResponse : global::ProtoBuf.IExtensible
  {
    public SettleResponse() {}
    
    private int _star = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private int _reward = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private battle.SettleResourse _resource = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public battle.SettleResourse resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HarvestNotify")]
  public partial class HarvestNotify : global::ProtoBuf.IExtensible
  {
    public HarvestNotify() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HarvestPullRequest")]
  public partial class HarvestPullRequest : global::ProtoBuf.IExtensible
  {
    public HarvestPullRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HarvestPullResponse")]
  public partial class HarvestPullResponse : global::ProtoBuf.IExtensible
  {
    public HarvestPullResponse() {}
    
    private readonly global::System.Collections.Generic.List<battle.HarvestPullResponse.SoldierPosInfo> _soldierinfos = new global::System.Collections.Generic.List<battle.HarvestPullResponse.SoldierPosInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"soldierinfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<battle.HarvestPullResponse.SoldierPosInfo> soldierinfos
    {
      get { return _soldierinfos; }
    }
  
    private string _map = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string map
    {
      get { return _map; }
      set { _map = value; }
    }
    private string _shape = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"shape", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string shape
    {
      get { return _shape; }
      set { _shape = value; }
    }
    private int _width = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }
    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierPosInfo")]
  public partial class SoldierPosInfo : global::ProtoBuf.IExtensible
  {
    public SoldierPosInfo() {}
    
    private int _cx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cx
    {
      get { return _cx; }
      set { _cx = value; }
    }
    private int _cy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cy
    {
      get { return _cy; }
      set { _cy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HarvestPickupRequest")]
  public partial class HarvestPickupRequest : global::ProtoBuf.IExtensible
  {
    public HarvestPickupRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HarvestPickupResponse")]
  public partial class HarvestPickupResponse : global::ProtoBuf.IExtensible
  {
    public HarvestPickupResponse() {}
    
    private readonly global::System.Collections.Generic.List<battle.HarvestPickupResponse.PickupMessage> _item = new global::System.Collections.Generic.List<battle.HarvestPickupResponse.PickupMessage>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<battle.HarvestPickupResponse.PickupMessage> item
    {
      get { return _item; }
    }
  
    private readonly global::System.Collections.Generic.List<battle.HarvestPickupResponse.PickupMessage> _coin = new global::System.Collections.Generic.List<battle.HarvestPickupResponse.PickupMessage>();
    [global::ProtoBuf.ProtoMember(2, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<battle.HarvestPickupResponse.PickupMessage> coin
    {
      get { return _coin; }
    }
  
    private readonly global::System.Collections.Generic.List<battle.HarvestPickupResponse.PickupMessage> _diamond = new global::System.Collections.Generic.List<battle.HarvestPickupResponse.PickupMessage>();
    [global::ProtoBuf.ProtoMember(3, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<battle.HarvestPickupResponse.PickupMessage> diamond
    {
      get { return _diamond; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PickupMessage")]
  public partial class PickupMessage : global::ProtoBuf.IExtensible
  {
    public PickupMessage() {}
    
    private int _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private int _cx;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cx
    {
      get { return _cx; }
      set { _cx = value; }
    }
    private int _cy;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cy
    {
      get { return _cy; }
      set { _cy = value; }
    }
    private int _itemid = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}