//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: build.proto
namespace build
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildInfo")]
  public partial class BuildInfo : global::ProtoBuf.IExtensible
  {
    public BuildInfo() {}
    
    private int _action = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _uid = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _id = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _buildtype = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buildtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int buildtype
    {
      get { return _buildtype; }
      set { _buildtype = value; }
    }
    private int _level = (int)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _starlevel = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"starlevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int starlevel
    {
      get { return _starlevel; }
      set { _starlevel = value; }
    }
    private int _quality = (int)-1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildInfoRequest")]
  public partial class BuildInfoRequest : global::ProtoBuf.IExtensible
  {
    public BuildInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildInfoResponse")]
  public partial class BuildInfoResponse : global::ProtoBuf.IExtensible
  {
    public BuildInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<build.BuildInfo> _build_info = new global::System.Collections.Generic.List<build.BuildInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"build_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<build.BuildInfo> build_info
    {
      get { return _build_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildLevelUpRequest")]
  public partial class BuildLevelUpRequest : global::ProtoBuf.IExtensible
  {
    public BuildLevelUpRequest() {}
    
    private int _buildid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"buildid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buildid
    {
      get { return _buildid; }
      set { _buildid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildLevelUpResponse")]
  public partial class BuildLevelUpResponse : global::ProtoBuf.IExtensible
  {
    public BuildLevelUpResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildQualityUpRequest")]
  public partial class BuildQualityUpRequest : global::ProtoBuf.IExtensible
  {
    public BuildQualityUpRequest() {}
    
    private int _buildid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"buildid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buildid
    {
      get { return _buildid; }
      set { _buildid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildQualityUpResponse")]
  public partial class BuildQualityUpResponse : global::ProtoBuf.IExtensible
  {
    public BuildQualityUpResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildStarUpRequest")]
  public partial class BuildStarUpRequest : global::ProtoBuf.IExtensible
  {
    public BuildStarUpRequest() {}
    
    private int _buildid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"buildid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buildid
    {
      get { return _buildid; }
      set { _buildid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildStarUpResponse")]
  public partial class BuildStarUpResponse : global::ProtoBuf.IExtensible
  {
    public BuildStarUpResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildAnalyzeRequest")]
  public partial class BuildAnalyzeRequest : global::ProtoBuf.IExtensible
  {
    public BuildAnalyzeRequest() {}
    
    private int _buildid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"buildid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buildid
    {
      get { return _buildid; }
      set { _buildid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildAnalyzeResponse")]
  public partial class BuildAnalyzeResponse : global::ProtoBuf.IExtensible
  {
    public BuildAnalyzeResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildComposeRequest")]
  public partial class BuildComposeRequest : global::ProtoBuf.IExtensible
  {
    public BuildComposeRequest() {}
    
    private int _buildtype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"buildtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buildtype
    {
      get { return _buildtype; }
      set { _buildtype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildComposeResponse")]
  public partial class BuildComposeResponse : global::ProtoBuf.IExtensible
  {
    public BuildComposeResponse() {}
    
    private int _buildtype = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"buildtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buildtype
    {
      get { return _buildtype; }
      set { _buildtype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}