//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: canvasedit.proto
namespace canvasedit
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipCanvasRequest")]
  public partial class ShipCanvasRequest : global::ProtoBuf.IExtensible
  {
    public ShipCanvasRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipCanvasInfo")]
  public partial class ShipCanvasInfo : global::ProtoBuf.IExtensible
  {
    public ShipCanvasInfo() {}
    
    private int _action = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _id = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _uid = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _designid = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"designid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int designid
    {
      get { return _designid; }
      set { _designid = value; }
    }
    private int _type = (int)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _name = @"null";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"null")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _width = (int)-1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }
    private int _height = (int)-1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
    private int _shift_cx = (int)-1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"shift_cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int shift_cx
    {
      get { return _shift_cx; }
      set { _shift_cx = value; }
    }
    private int _shift_cy = (int)-1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"shift_cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int shift_cy
    {
      get { return _shift_cy; }
      set { _shift_cy = value; }
    }
    private string _shape = @"null";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"shape", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"null")]
    public string shape
    {
      get { return _shape; }
      set { _shape = value; }
    }
    private string _map = @"null";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"null")]
    public string map
    {
      get { return _map; }
      set { _map = value; }
    }
    private int _bs_id = (int)-1;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"bs_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int bs_id
    {
      get { return _bs_id; }
      set { _bs_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipCanvasResponse")]
  public partial class ShipCanvasResponse : global::ProtoBuf.IExtensible
  {
    public ShipCanvasResponse() {}
    
    private readonly global::System.Collections.Generic.List<canvasedit.ShipCanvasInfo> _shipcanvas_infos = new global::System.Collections.Generic.List<canvasedit.ShipCanvasInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"shipcanvas_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<canvasedit.ShipCanvasInfo> shipcanvas_infos
    {
      get { return _shipcanvas_infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipDesignInfoRequest")]
  public partial class ShipDesignInfoRequest : global::ProtoBuf.IExtensible
  {
    public ShipDesignInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipDesignInfoResponse")]
  public partial class ShipDesignInfoResponse : global::ProtoBuf.IExtensible
  {
    public ShipDesignInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<canvasedit.ShipDesignInfoResponse.ShipDesignInfo> _shipdesign_infos = new global::System.Collections.Generic.List<canvasedit.ShipDesignInfoResponse.ShipDesignInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"shipdesign_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<canvasedit.ShipDesignInfoResponse.ShipDesignInfo> shipdesign_infos
    {
      get { return _shipdesign_infos; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipDesignInfo")]
  public partial class ShipDesignInfo : global::ProtoBuf.IExtensible
  {
    public ShipDesignInfo() {}
    
    private int _action = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _id = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _uid = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _shipcanvastypeid = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"shipcanvastypeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int shipcanvastypeid
    {
      get { return _shipcanvastypeid; }
      set { _shipcanvastypeid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipPutInfo")]
  public partial class ShipPutInfo : global::ProtoBuf.IExtensible
  {
    public ShipPutInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _objid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"objid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int objid
    {
      get { return _objid; }
      set { _objid = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _cx;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cx
    {
      get { return _cx; }
      set { _cx = value; }
    }
    private int _cy;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cy
    {
      get { return _cy; }
      set { _cy = value; }
    }
    private int _shipput_data0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"shipput_data0", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shipput_data0
    {
      get { return _shipput_data0; }
      set { _shipput_data0 = value; }
    }
    private int _shipput_data1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"shipput_data1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shipput_data1
    {
      get { return _shipput_data1; }
      set { _shipput_data1 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipCanvasModifyRequest")]
  public partial class ShipCanvasModifyRequest : global::ProtoBuf.IExtensible
  {
    public ShipCanvasModifyRequest() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _shift_cx;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"shift_cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shift_cx
    {
      get { return _shift_cx; }
      set { _shift_cx = value; }
    }
    private int _shift_cy;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"shift_cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shift_cy
    {
      get { return _shift_cy; }
      set { _shift_cy = value; }
    }
    private readonly global::System.Collections.Generic.List<canvasedit.ShipPutInfo> _shipput_infos = new global::System.Collections.Generic.List<canvasedit.ShipPutInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"shipput_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<canvasedit.ShipPutInfo> shipput_infos
    {
      get { return _shipput_infos; }
    }
  
    private int _bs_id = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bs_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bs_id
    {
      get { return _bs_id; }
      set { _bs_id = value; }
    }
    private int _designid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"designid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int designid
    {
      get { return _designid; }
      set { _designid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipCanvasModifyResponse")]
  public partial class ShipCanvasModifyResponse : global::ProtoBuf.IExtensible
  {
    public ShipCanvasModifyResponse() {}
    
    private readonly global::System.Collections.Generic.List<canvasedit.ShipCanvasModifyResponse.ModifyResponseInfo> _modify_info = new global::System.Collections.Generic.List<canvasedit.ShipCanvasModifyResponse.ModifyResponseInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"modify_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<canvasedit.ShipCanvasModifyResponse.ModifyResponseInfo> modify_info
    {
      get { return _modify_info; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModifyResponseInfo")]
  public partial class ModifyResponseInfo : global::ProtoBuf.IExtensible
  {
    public ModifyResponseInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _objid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"objid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int objid
    {
      get { return _objid; }
      set { _objid = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CanvasBuildRequest")]
  public partial class CanvasBuildRequest : global::ProtoBuf.IExtensible
  {
    public CanvasBuildRequest() {}
    
    private readonly global::System.Collections.Generic.List<int> _canvasids = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"canvasids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> canvasids
    {
      get { return _canvasids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CanvasBuildResponse")]
  public partial class CanvasBuildResponse : global::ProtoBuf.IExtensible
  {
    public CanvasBuildResponse() {}
    
    private readonly global::System.Collections.Generic.List<canvasedit.CanvasBuildResponse.CanvasBuildInfo> _canvasbuild_info = new global::System.Collections.Generic.List<canvasedit.CanvasBuildResponse.CanvasBuildInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"canvasbuild_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<canvasedit.CanvasBuildResponse.CanvasBuildInfo> canvasbuild_info
    {
      get { return _canvasbuild_info; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CanvasBuildInfo")]
  public partial class CanvasBuildInfo : global::ProtoBuf.IExtensible
  {
    public CanvasBuildInfo() {}
    
    private int _canvasid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"canvasid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int canvasid
    {
      get { return _canvasid; }
      set { _canvasid = value; }
    }
    private readonly global::System.Collections.Generic.List<canvasedit.ShipPutInfo> _shipput_info = new global::System.Collections.Generic.List<canvasedit.ShipPutInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"shipput_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<canvasedit.ShipPutInfo> shipput_info
    {
      get { return _shipput_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipCanvasModifyNameRequest")]
  public partial class ShipCanvasModifyNameRequest : global::ProtoBuf.IExtensible
  {
    public ShipCanvasModifyNameRequest() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipCanvasModifyNameResponse")]
  public partial class ShipCanvasModifyNameResponse : global::ProtoBuf.IExtensible
  {
    public ShipCanvasModifyNameResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}