//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ernie.proto
namespace ernie
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErnieRewardInfo")]
  public partial class ErnieRewardInfo : global::ProtoBuf.IExtensible
  {
    public ErnieRewardInfo() {}
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private bool _issoul = (bool)false;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"issoul", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool issoul
    {
      get { return _issoul; }
      set { _issoul = value; }
    }
    private bool _isbook = (bool)false;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isbook", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool isbook
    {
      get { return _isbook; }
      set { _isbook = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErnieCoinRequest")]
  public partial class ErnieCoinRequest : global::ProtoBuf.IExtensible
  {
    public ErnieCoinRequest() {}
    
    private bool _istenhit = (bool)false;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"istenhit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool istenhit
    {
      get { return _istenhit; }
      set { _istenhit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErnieCoinResponse")]
  public partial class ErnieCoinResponse : global::ProtoBuf.IExtensible
  {
    public ErnieCoinResponse() {}
    
    private readonly global::System.Collections.Generic.List<ernie.ErnieRewardInfo> _reward_info = new global::System.Collections.Generic.List<ernie.ErnieRewardInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"reward_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ernie.ErnieRewardInfo> reward_info
    {
      get { return _reward_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErnieDiamondRequest")]
  public partial class ErnieDiamondRequest : global::ProtoBuf.IExtensible
  {
    public ErnieDiamondRequest() {}
    
    private bool _istenhit = (bool)false;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"istenhit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool istenhit
    {
      get { return _istenhit; }
      set { _istenhit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErnieDiamondResponse")]
  public partial class ErnieDiamondResponse : global::ProtoBuf.IExtensible
  {
    public ErnieDiamondResponse() {}
    
    private readonly global::System.Collections.Generic.List<ernie.ErnieRewardInfo> _reward_info = new global::System.Collections.Generic.List<ernie.ErnieRewardInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"reward_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ernie.ErnieRewardInfo> reward_info
    {
      get { return _reward_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErnieSoulRequest")]
  public partial class ErnieSoulRequest : global::ProtoBuf.IExtensible
  {
    public ErnieSoulRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErnieSoulResponse")]
  public partial class ErnieSoulResponse : global::ProtoBuf.IExtensible
  {
    public ErnieSoulResponse() {}
    
    private readonly global::System.Collections.Generic.List<ernie.ErnieRewardInfo> _reward_info = new global::System.Collections.Generic.List<ernie.ErnieRewardInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"reward_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ernie.ErnieRewardInfo> reward_info
    {
      get { return _reward_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErnieUserInfoRequest")]
  public partial class ErnieUserInfoRequest : global::ProtoBuf.IExtensible
  {
    public ErnieUserInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErnieUserInfoResponse")]
  public partial class ErnieUserInfoResponse : global::ProtoBuf.IExtensible
  {
    public ErnieUserInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<ernie.ErnieUserInfoResponse.ErnieInfo> _ernie_infos = new global::System.Collections.Generic.List<ernie.ErnieUserInfoResponse.ErnieInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ernie_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ernie.ErnieUserInfoResponse.ErnieInfo> ernie_infos
    {
      get { return _ernie_infos; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErnieInfo")]
  public partial class ErnieInfo : global::ProtoBuf.IExtensible
  {
    public ErnieInfo() {}
    
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _uid = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _ernie_type = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ernie_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ernie_type
    {
      get { return _ernie_type; }
      set { _ernie_type = value; }
    }
    private int _history_times = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"history_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int history_times
    {
      get { return _history_times; }
      set { _history_times = value; }
    }
    private int _last_time = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"last_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int last_time
    {
      get { return _last_time; }
      set { _last_time = value; }
    }
    private int _last_free_time = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"last_free_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int last_free_time
    {
      get { return _last_free_time; }
      set { _last_free_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}