//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: fruition.proto
namespace fruition
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FruitionInfoRequest")]
  public partial class FruitionInfoRequest : global::ProtoBuf.IExtensible
  {
    public FruitionInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FruitionInfoResponse")]
  public partial class FruitionInfoResponse : global::ProtoBuf.IExtensible
  {
    public FruitionInfoResponse() {}
    
    private int _action = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _uid = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _current_fvalue = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"current_fvalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int current_fvalue
    {
      get { return _current_fvalue; }
      set { _current_fvalue = value; }
    }
    private int _highest_fvalue = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"highest_fvalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int highest_fvalue
    {
      get { return _highest_fvalue; }
      set { _highest_fvalue = value; }
    }
    private long _mask0 = (long)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"mask0", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long mask0
    {
      get { return _mask0; }
      set { _mask0 = value; }
    }
    private long _mask1 = (long)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mask1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long mask1
    {
      get { return _mask1; }
      set { _mask1 = value; }
    }
    private long _mask2 = (long)-1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mask2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long mask2
    {
      get { return _mask2; }
      set { _mask2 = value; }
    }
    private long _mask3 = (long)-1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mask3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long mask3
    {
      get { return _mask3; }
      set { _mask3 = value; }
    }
    private long _mask4 = (long)-1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"mask4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long mask4
    {
      get { return _mask4; }
      set { _mask4 = value; }
    }
    private long _mask5 = (long)-1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"mask5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long mask5
    {
      get { return _mask5; }
      set { _mask5 = value; }
    }
    private long _mask6 = (long)-1;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"mask6", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long mask6
    {
      get { return _mask6; }
      set { _mask6 = value; }
    }
    private long _mask7 = (long)-1;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"mask7", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long mask7
    {
      get { return _mask7; }
      set { _mask7 = value; }
    }
    private long _mask8 = (long)-1;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"mask8", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long mask8
    {
      get { return _mask8; }
      set { _mask8 = value; }
    }
    private long _mask9 = (long)-1;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"mask9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long mask9
    {
      get { return _mask9; }
      set { _mask9 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FruitionNearTimeRequest")]
  public partial class FruitionNearTimeRequest : global::ProtoBuf.IExtensible
  {
    public FruitionNearTimeRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FruitionNearTimeResponse")]
  public partial class FruitionNearTimeResponse : global::ProtoBuf.IExtensible
  {
    public FruitionNearTimeResponse() {}
    
    private readonly global::System.Collections.Generic.List<fruition.FruitionNearTimeResponse.NearInfo> _info = new global::System.Collections.Generic.List<fruition.FruitionNearTimeResponse.NearInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fruition.FruitionNearTimeResponse.NearInfo> info
    {
      get { return _info; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NearInfo")]
  public partial class NearInfo : global::ProtoBuf.IExtensible
  {
    public NearInfo() {}
    
    private int _fruition_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fruition_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fruition_id
    {
      get { return _fruition_id; }
      set { _fruition_id = value; }
    }
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatisticInfo")]
  public partial class StatisticInfo : global::ProtoBuf.IExtensible
  {
    public StatisticInfo() {}
    
    private int _action = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _id = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _uid = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _type = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private long _value = (long)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatisticInfoRequest")]
  public partial class StatisticInfoRequest : global::ProtoBuf.IExtensible
  {
    public StatisticInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatisticInfoResponse")]
  public partial class StatisticInfoResponse : global::ProtoBuf.IExtensible
  {
    public StatisticInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<fruition.StatisticInfo> _infos = new global::System.Collections.Generic.List<fruition.StatisticInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fruition.StatisticInfo> infos
    {
      get { return _infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}