//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gate.proto
namespace gate
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Header")]
  public partial class Header : global::ProtoBuf.IExtensible
  {
    public Header() {}
    
    private int _uid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _device_type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"device_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int device_type
    {
      get { return _device_type; }
      set { _device_type = value; }
    }
    private string _client_version = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"client_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string client_version
    {
      get { return _client_version; }
      set { _client_version = value; }
    }
    private float _profile = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"profile", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float profile
    {
      get { return _profile; }
      set { _profile = value; }
    }
    private string _internal_version = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"internal_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string internal_version
    {
      get { return _internal_version; }
      set { _internal_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErrorMessage")]
  public partial class ErrorMessage : global::ProtoBuf.IExtensible
  {
    public ErrorMessage() {}
    
    private int _code = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private string _description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Command")]
  public partial class Command : global::ProtoBuf.IExtensible
  {
    public Command() {}
    
    private gate.Command.CMD _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public gate.Command.CMD id
    {
      get { return _id; }
      set { _id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"CMD")]
    public enum CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1", Value=1)]
      CMD_1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_100", Value=100)]
      CMD_100 = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_107", Value=107)]
      CMD_107 = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_108", Value=108)]
      CMD_108 = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_111", Value=111)]
      CMD_111 = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_112", Value=112)]
      CMD_112 = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_201", Value=201)]
      CMD_201 = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_202", Value=202)]
      CMD_202 = 202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_203", Value=203)]
      CMD_203 = 203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_204", Value=204)]
      CMD_204 = 204,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_205", Value=205)]
      CMD_205 = 205,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_206", Value=206)]
      CMD_206 = 206,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_207", Value=207)]
      CMD_207 = 207,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_208", Value=208)]
      CMD_208 = 208,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_209", Value=209)]
      CMD_209 = 209,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_210", Value=210)]
      CMD_210 = 210,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_211", Value=211)]
      CMD_211 = 211,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_212", Value=212)]
      CMD_212 = 212,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_213", Value=213)]
      CMD_213 = 213,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_214", Value=214)]
      CMD_214 = 214,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_301", Value=301)]
      CMD_301 = 301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_302", Value=302)]
      CMD_302 = 302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_303", Value=303)]
      CMD_303 = 303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_304", Value=304)]
      CMD_304 = 304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_305", Value=305)]
      CMD_305 = 305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_306", Value=306)]
      CMD_306 = 306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_307", Value=307)]
      CMD_307 = 307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_308", Value=308)]
      CMD_308 = 308,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_309", Value=309)]
      CMD_309 = 309,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_311", Value=311)]
      CMD_311 = 311,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_312", Value=312)]
      CMD_312 = 312,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_313", Value=313)]
      CMD_313 = 313,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_314", Value=314)]
      CMD_314 = 314,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_400", Value=400)]
      CMD_400 = 400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_401", Value=401)]
      CMD_401 = 401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_402", Value=402)]
      CMD_402 = 402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_403", Value=403)]
      CMD_403 = 403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_404", Value=404)]
      CMD_404 = 404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_405", Value=405)]
      CMD_405 = 405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_406", Value=406)]
      CMD_406 = 406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_503", Value=503)]
      CMD_503 = 503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_504", Value=504)]
      CMD_504 = 504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_505", Value=505)]
      CMD_505 = 505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_506", Value=506)]
      CMD_506 = 506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_507", Value=507)]
      CMD_507 = 507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_508", Value=508)]
      CMD_508 = 508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_509", Value=509)]
      CMD_509 = 509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_510", Value=510)]
      CMD_510 = 510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_511", Value=511)]
      CMD_511 = 511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_512", Value=512)]
      CMD_512 = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_513", Value=513)]
      CMD_513 = 513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_514", Value=514)]
      CMD_514 = 514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_605", Value=605)]
      CMD_605 = 605,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_606", Value=606)]
      CMD_606 = 606,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_609", Value=609)]
      CMD_609 = 609,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_610", Value=610)]
      CMD_610 = 610,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_611", Value=611)]
      CMD_611 = 611,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_612", Value=612)]
      CMD_612 = 612,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_617", Value=617)]
      CMD_617 = 617,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_619", Value=619)]
      CMD_619 = 619,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_620", Value=620)]
      CMD_620 = 620,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_623", Value=623)]
      CMD_623 = 623,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_624", Value=624)]
      CMD_624 = 624,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_625", Value=625)]
      CMD_625 = 625,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_626", Value=626)]
      CMD_626 = 626,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_627", Value=627)]
      CMD_627 = 627,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_628", Value=628)]
      CMD_628 = 628,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_629", Value=629)]
      CMD_629 = 629,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_630", Value=630)]
      CMD_630 = 630,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_631", Value=631)]
      CMD_631 = 631,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_632", Value=632)]
      CMD_632 = 632,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_701", Value=701)]
      CMD_701 = 701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_702", Value=702)]
      CMD_702 = 702,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_703", Value=703)]
      CMD_703 = 703,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_704", Value=704)]
      CMD_704 = 704,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_705", Value=705)]
      CMD_705 = 705,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_706", Value=706)]
      CMD_706 = 706,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_707", Value=707)]
      CMD_707 = 707,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_708", Value=708)]
      CMD_708 = 708,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_709", Value=709)]
      CMD_709 = 709,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_710", Value=710)]
      CMD_710 = 710,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_711", Value=711)]
      CMD_711 = 711,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_712", Value=712)]
      CMD_712 = 712,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_713", Value=713)]
      CMD_713 = 713,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_714", Value=714)]
      CMD_714 = 714,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_715", Value=715)]
      CMD_715 = 715,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_716", Value=716)]
      CMD_716 = 716,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_717", Value=717)]
      CMD_717 = 717,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_718", Value=718)]
      CMD_718 = 718,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_801", Value=801)]
      CMD_801 = 801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_802", Value=802)]
      CMD_802 = 802,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_803", Value=803)]
      CMD_803 = 803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_804", Value=804)]
      CMD_804 = 804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_805", Value=805)]
      CMD_805 = 805,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_806", Value=806)]
      CMD_806 = 806,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_807", Value=807)]
      CMD_807 = 807,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_808", Value=808)]
      CMD_808 = 808,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_809", Value=809)]
      CMD_809 = 809,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_810", Value=810)]
      CMD_810 = 810,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_901", Value=901)]
      CMD_901 = 901,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_902", Value=902)]
      CMD_902 = 902,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_903", Value=903)]
      CMD_903 = 903,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_904", Value=904)]
      CMD_904 = 904,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_905", Value=905)]
      CMD_905 = 905,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_906", Value=906)]
      CMD_906 = 906,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_907", Value=907)]
      CMD_907 = 907,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_908", Value=908)]
      CMD_908 = 908,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_909", Value=909)]
      CMD_909 = 909,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_910", Value=910)]
      CMD_910 = 910,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_911", Value=911)]
      CMD_911 = 911,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_912", Value=912)]
      CMD_912 = 912,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1001", Value=1001)]
      CMD_1001 = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1002", Value=1002)]
      CMD_1002 = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1003", Value=1003)]
      CMD_1003 = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1004", Value=1004)]
      CMD_1004 = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1005", Value=1005)]
      CMD_1005 = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1006", Value=1006)]
      CMD_1006 = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1007", Value=1007)]
      CMD_1007 = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1008", Value=1008)]
      CMD_1008 = 1008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1011", Value=1011)]
      CMD_1011 = 1011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1012", Value=1012)]
      CMD_1012 = 1012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1013", Value=1013)]
      CMD_1013 = 1013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1014", Value=1014)]
      CMD_1014 = 1014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1015", Value=1015)]
      CMD_1015 = 1015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1016", Value=1016)]
      CMD_1016 = 1016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1017", Value=1017)]
      CMD_1017 = 1017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1018", Value=1018)]
      CMD_1018 = 1018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1019", Value=1019)]
      CMD_1019 = 1019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1020", Value=1020)]
      CMD_1020 = 1020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1021", Value=1021)]
      CMD_1021 = 1021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1022", Value=1022)]
      CMD_1022 = 1022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1023", Value=1023)]
      CMD_1023 = 1023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1024", Value=1024)]
      CMD_1024 = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1025", Value=1025)]
      CMD_1025 = 1025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1026", Value=1026)]
      CMD_1026 = 1026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1101", Value=1101)]
      CMD_1101 = 1101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1102", Value=1102)]
      CMD_1102 = 1102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1103", Value=1103)]
      CMD_1103 = 1103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1104", Value=1104)]
      CMD_1104 = 1104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1105", Value=1105)]
      CMD_1105 = 1105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1106", Value=1106)]
      CMD_1106 = 1106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1107", Value=1107)]
      CMD_1107 = 1107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1108", Value=1108)]
      CMD_1108 = 1108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1201", Value=1201)]
      CMD_1201 = 1201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1202", Value=1202)]
      CMD_1202 = 1202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1203", Value=1203)]
      CMD_1203 = 1203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1204", Value=1204)]
      CMD_1204 = 1204,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1205", Value=1205)]
      CMD_1205 = 1205,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1206", Value=1206)]
      CMD_1206 = 1206,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1301", Value=1301)]
      CMD_1301 = 1301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1302", Value=1302)]
      CMD_1302 = 1302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1303", Value=1303)]
      CMD_1303 = 1303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1304", Value=1304)]
      CMD_1304 = 1304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1305", Value=1305)]
      CMD_1305 = 1305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1306", Value=1306)]
      CMD_1306 = 1306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1401", Value=1401)]
      CMD_1401 = 1401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1402", Value=1402)]
      CMD_1402 = 1402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1403", Value=1403)]
      CMD_1403 = 1403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1404", Value=1404)]
      CMD_1404 = 1404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1405", Value=1405)]
      CMD_1405 = 1405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1406", Value=1406)]
      CMD_1406 = 1406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1407", Value=1407)]
      CMD_1407 = 1407,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1408", Value=1408)]
      CMD_1408 = 1408,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1409", Value=1409)]
      CMD_1409 = 1409,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1410", Value=1410)]
      CMD_1410 = 1410,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1411", Value=1411)]
      CMD_1411 = 1411,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1412", Value=1412)]
      CMD_1412 = 1412,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1413", Value=1413)]
      CMD_1413 = 1413,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1414", Value=1414)]
      CMD_1414 = 1414,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1415", Value=1415)]
      CMD_1415 = 1415,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1416", Value=1416)]
      CMD_1416 = 1416,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1418", Value=1418)]
      CMD_1418 = 1418,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1419", Value=1419)]
      CMD_1419 = 1419,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1420", Value=1420)]
      CMD_1420 = 1420,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1501", Value=1501)]
      CMD_1501 = 1501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1502", Value=1502)]
      CMD_1502 = 1502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1503", Value=1503)]
      CMD_1503 = 1503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1504", Value=1504)]
      CMD_1504 = 1504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1505", Value=1505)]
      CMD_1505 = 1505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1506", Value=1506)]
      CMD_1506 = 1506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1507", Value=1507)]
      CMD_1507 = 1507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1508", Value=1508)]
      CMD_1508 = 1508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1601", Value=1601)]
      CMD_1601 = 1601,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1602", Value=1602)]
      CMD_1602 = 1602,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1603", Value=1603)]
      CMD_1603 = 1603,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1604", Value=1604)]
      CMD_1604 = 1604,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1605", Value=1605)]
      CMD_1605 = 1605,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1606", Value=1606)]
      CMD_1606 = 1606,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1607", Value=1607)]
      CMD_1607 = 1607,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1608", Value=1608)]
      CMD_1608 = 1608,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1609", Value=1609)]
      CMD_1609 = 1609,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1610", Value=1610)]
      CMD_1610 = 1610,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1701", Value=1701)]
      CMD_1701 = 1701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1702", Value=1702)]
      CMD_1702 = 1702,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1703", Value=1703)]
      CMD_1703 = 1703,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_1704", Value=1704)]
      CMD_1704 = 1704
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GateMessage")]
  public partial class GateMessage : global::ProtoBuf.IExtensible
  {
    public GateMessage() {}
    
    private gate.Header _head = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public gate.Header head
    {
      get { return _head; }
      set { _head = value; }
    }
    private readonly global::System.Collections.Generic.List<gate.GateMessage.MessageContent> _content = new global::System.Collections.Generic.List<gate.GateMessage.MessageContent>();
    [global::ProtoBuf.ProtoMember(2, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<gate.GateMessage.MessageContent> content
    {
      get { return _content; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageContent")]
  public partial class MessageContent : global::ProtoBuf.IExtensible
  {
    public MessageContent() {}
    
    private int _cmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private string _proto_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"proto_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string proto_name
    {
      get { return _proto_name; }
      set { _proto_name = value; }
    }
    private byte[] _network_message = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"network_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] network_message
    {
      get { return _network_message; }
      set { _network_message = value; }
    }
    private gate.ErrorMessage _error_message = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"error_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public gate.ErrorMessage error_message
    {
      get { return _error_message; }
      set { _error_message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogoutRequest")]
  public partial class LogoutRequest : global::ProtoBuf.IExtensible
  {
    public LogoutRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}