//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: item.proto
namespace item
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemInfo")]
  public partial class ItemInfo : global::ProtoBuf.IExtensible
  {
    public ItemInfo() {}
    
    private int _action = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _id = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _itemtypeid = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"itemtypeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int itemtypeid
    {
      get { return _itemtypeid; }
      set { _itemtypeid = value; }
    }
    private int _superpose = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"superpose", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int superpose
    {
      get { return _superpose; }
      set { _superpose = value; }
    }
    private int _position = (int)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _uid = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemInfoRequest")]
  public partial class ItemInfoRequest : global::ProtoBuf.IExtensible
  {
    public ItemInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemInfoResponse")]
  public partial class ItemInfoResponse : global::ProtoBuf.IExtensible
  {
    public ItemInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<item.ItemInfo> _item_infos = new global::System.Collections.Generic.List<item.ItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<item.ItemInfo> item_infos
    {
      get { return _item_infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemUseRequest")]
  public partial class ItemUseRequest : global::ProtoBuf.IExtensible
  {
    public ItemUseRequest() {}
    
    private int _item_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _to_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"to_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int to_id
    {
      get { return _to_id; }
      set { _to_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemUseResponse")]
  public partial class ItemUseResponse : global::ProtoBuf.IExtensible
  {
    public ItemUseResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemBatchUseRequest")]
  public partial class ItemBatchUseRequest : global::ProtoBuf.IExtensible
  {
    public ItemBatchUseRequest() {}
    
    private readonly global::System.Collections.Generic.List<item.ItemBatchUseRequest.ItemUseInfo> _use_infos = new global::System.Collections.Generic.List<item.ItemBatchUseRequest.ItemUseInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"use_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<item.ItemBatchUseRequest.ItemUseInfo> use_infos
    {
      get { return _use_infos; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemUseInfo")]
  public partial class ItemUseInfo : global::ProtoBuf.IExtensible
  {
    public ItemUseInfo() {}
    
    private int _item_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _to_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"to_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int to_id
    {
      get { return _to_id; }
      set { _to_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemBatchUseResponse")]
  public partial class ItemBatchUseResponse : global::ProtoBuf.IExtensible
  {
    public ItemBatchUseResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipComposeRequest")]
  public partial class EquipComposeRequest : global::ProtoBuf.IExtensible
  {
    public EquipComposeRequest() {}
    
    private int _itemtypeid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemtypeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemtypeid
    {
      get { return _itemtypeid; }
      set { _itemtypeid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipComposeResponse")]
  public partial class EquipComposeResponse : global::ProtoBuf.IExtensible
  {
    public EquipComposeResponse() {}
    
    private int _ditem_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ditem_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ditem_id
    {
      get { return _ditem_id; }
      set { _ditem_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemSellRequest")]
  public partial class ItemSellRequest : global::ProtoBuf.IExtensible
  {
    public ItemSellRequest() {}
    
    private readonly global::System.Collections.Generic.List<item.ItemSellRequest.ItemSellInfo> _sell_list = new global::System.Collections.Generic.List<item.ItemSellRequest.ItemSellInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"sell_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<item.ItemSellRequest.ItemSellInfo> sell_list
    {
      get { return _sell_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemSellInfo")]
  public partial class ItemSellInfo : global::ProtoBuf.IExtensible
  {
    public ItemSellInfo() {}
    
    private int _itemid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private int _sellnum = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sellnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sellnum
    {
      get { return _sellnum; }
      set { _sellnum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemSellResponse")]
  public partial class ItemSellResponse : global::ProtoBuf.IExtensible
  {
    public ItemSellResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}