//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mail.proto
namespace mail
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailInfoRequest")]
  public partial class MailInfoRequest : global::ProtoBuf.IExtensible
  {
    public MailInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailInfo")]
  public partial class MailInfo : global::ProtoBuf.IExtensible
  {
    public MailInfo() {}
    
    private int _action = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _id = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _uid = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _sendtime = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sendtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int sendtime
    {
      get { return _sendtime; }
      set { _sendtime = value; }
    }
    private int _deltime = (int)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"deltime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int deltime
    {
      get { return _deltime; }
      set { _deltime = value; }
    }
    private int _recvtime = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"recvtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int recvtime
    {
      get { return _recvtime; }
      set { _recvtime = value; }
    }
    private string _sendname = @"null";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sendname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"null")]
    public string sendname
    {
      get { return _sendname; }
      set { _sendname = value; }
    }
    private string _title = @"null";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"null")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _appendix = @"null";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"appendix", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"null")]
    public string appendix
    {
      get { return _appendix; }
      set { _appendix = value; }
    }
    private string _message = @"null";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"null")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private int _flag = (int)-1;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailInfoResponse")]
  public partial class MailInfoResponse : global::ProtoBuf.IExtensible
  {
    public MailInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<mail.MailInfo> _mail_infos = new global::System.Collections.Generic.List<mail.MailInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mail_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mail.MailInfo> mail_infos
    {
      get { return _mail_infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailReadRequest")]
  public partial class MailReadRequest : global::ProtoBuf.IExtensible
  {
    public MailReadRequest() {}
    
    private int _mailid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailid
    {
      get { return _mailid; }
      set { _mailid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailReadResponse")]
  public partial class MailReadResponse : global::ProtoBuf.IExtensible
  {
    public MailReadResponse() {}
    
    private int _mailid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailid
    {
      get { return _mailid; }
      set { _mailid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailGetAppendixRequest")]
  public partial class MailGetAppendixRequest : global::ProtoBuf.IExtensible
  {
    public MailGetAppendixRequest() {}
    
    private int _mailid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailid
    {
      get { return _mailid; }
      set { _mailid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailGetAppendixResponse")]
  public partial class MailGetAppendixResponse : global::ProtoBuf.IExtensible
  {
    public MailGetAppendixResponse() {}
    
    private int _mailid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailid
    {
      get { return _mailid; }
      set { _mailid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}