//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: qa.proto
namespace qa
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecoveryPhysicalOfflineRequest")]
  public partial class RecoveryPhysicalOfflineRequest : global::ProtoBuf.IExtensible
  {
    public RecoveryPhysicalOfflineRequest() {}
    
    private int _offline_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"offline_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int offline_time
    {
      get { return _offline_time; }
      set { _offline_time = value; }
    }
    private int _online_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"online_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int online_time
    {
      get { return _online_time; }
      set { _online_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecoveryPhysicalOfflineResponse")]
  public partial class RecoveryPhysicalOfflineResponse : global::ProtoBuf.IExtensible
  {
    public RecoveryPhysicalOfflineResponse() {}
    
    private int _physical;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"physical", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int physical
    {
      get { return _physical; }
      set { _physical = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SvrTimeRequest")]
  public partial class SvrTimeRequest : global::ProtoBuf.IExtensible
  {
    public SvrTimeRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SvrTimeResponse")]
  public partial class SvrTimeResponse : global::ProtoBuf.IExtensible
  {
    public SvrTimeResponse() {}
    
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}