//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: soldier.proto
namespace soldier
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierInfo")]
  public partial class SoldierInfo : global::ProtoBuf.IExtensible
  {
    public SoldierInfo() {}
    
    private int _action = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _uid = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _id = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _soldiertypeid = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"soldiertypeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int soldiertypeid
    {
      get { return _soldiertypeid; }
      set { _soldiertypeid = value; }
    }
    private int _level = (int)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _starlevel = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"starlevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int starlevel
    {
      get { return _starlevel; }
      set { _starlevel = value; }
    }
    private int _exp = (int)-1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _quality = (int)-1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private int _askill_level = (int)-1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"askill_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int askill_level
    {
      get { return _askill_level; }
      set { _askill_level = value; }
    }
    private int _skill1_level = (int)-1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"skill1_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int skill1_level
    {
      get { return _skill1_level; }
      set { _skill1_level = value; }
    }
    private int _skill2_level = (int)-1;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"skill2_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int skill2_level
    {
      get { return _skill2_level; }
      set { _skill2_level = value; }
    }
    private int _skill3_level = (int)-1;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"skill3_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int skill3_level
    {
      get { return _skill3_level; }
      set { _skill3_level = value; }
    }
    private int _skill4_level = (int)-1;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"skill4_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int skill4_level
    {
      get { return _skill4_level; }
      set { _skill4_level = value; }
    }
    private int _skill5_level = (int)-1;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"skill5_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int skill5_level
    {
      get { return _skill5_level; }
      set { _skill5_level = value; }
    }
    private int _equipment0 = (int)-1;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"equipment0", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int equipment0
    {
      get { return _equipment0; }
      set { _equipment0 = value; }
    }
    private int _equipment1 = (int)-1;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"equipment1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int equipment1
    {
      get { return _equipment1; }
      set { _equipment1 = value; }
    }
    private int _equipment2 = (int)-1;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"equipment2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int equipment2
    {
      get { return _equipment2; }
      set { _equipment2 = value; }
    }
    private int _equipment3 = (int)-1;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"equipment3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int equipment3
    {
      get { return _equipment3; }
      set { _equipment3 = value; }
    }
    private int _equipment4 = (int)-1;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"equipment4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int equipment4
    {
      get { return _equipment4; }
      set { _equipment4 = value; }
    }
    private int _equipment5 = (int)-1;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"equipment5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int equipment5
    {
      get { return _equipment5; }
      set { _equipment5 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierInfoRequest")]
  public partial class SoldierInfoRequest : global::ProtoBuf.IExtensible
  {
    public SoldierInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierInfoResponse")]
  public partial class SoldierInfoResponse : global::ProtoBuf.IExtensible
  {
    public SoldierInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<soldier.SoldierInfo> _soldier_info = new global::System.Collections.Generic.List<soldier.SoldierInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"soldier_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<soldier.SoldierInfo> soldier_info
    {
      get { return _soldier_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierStarUpRequest")]
  public partial class SoldierStarUpRequest : global::ProtoBuf.IExtensible
  {
    public SoldierStarUpRequest() {}
    
    private int _dsoldier_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dsoldier_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dsoldier_id
    {
      get { return _dsoldier_id; }
      set { _dsoldier_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierStarUpResponse")]
  public partial class SoldierStarUpResponse : global::ProtoBuf.IExtensible
  {
    public SoldierStarUpResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierSummonRequest")]
  public partial class SoldierSummonRequest : global::ProtoBuf.IExtensible
  {
    public SoldierSummonRequest() {}
    
    private int _soldiertypeid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"soldiertypeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int soldiertypeid
    {
      get { return _soldiertypeid; }
      set { _soldiertypeid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierSummonResponse")]
  public partial class SoldierSummonResponse : global::ProtoBuf.IExtensible
  {
    public SoldierSummonResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierEquipRequest")]
  public partial class SoldierEquipRequest : global::ProtoBuf.IExtensible
  {
    public SoldierEquipRequest() {}
    
    private int _soldier_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"soldier_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int soldier_id
    {
      get { return _soldier_id; }
      set { _soldier_id = value; }
    }
    private int _equip_pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equip_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_pos
    {
      get { return _equip_pos; }
      set { _equip_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierEquipResponse")]
  public partial class SoldierEquipResponse : global::ProtoBuf.IExtensible
  {
    public SoldierEquipResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierQualityUpRequest")]
  public partial class SoldierQualityUpRequest : global::ProtoBuf.IExtensible
  {
    public SoldierQualityUpRequest() {}
    
    private int _soldier_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"soldier_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int soldier_id
    {
      get { return _soldier_id; }
      set { _soldier_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierQualityUpResponse")]
  public partial class SoldierQualityUpResponse : global::ProtoBuf.IExtensible
  {
    public SoldierQualityUpResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierSkillUpRequest")]
  public partial class SoldierSkillUpRequest : global::ProtoBuf.IExtensible
  {
    public SoldierSkillUpRequest() {}
    
    private int _soldier_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"soldier_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int soldier_id
    {
      get { return _soldier_id; }
      set { _soldier_id = value; }
    }
    private int _skill_no;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_no
    {
      get { return _skill_no; }
      set { _skill_no = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierSkillUpResponse")]
  public partial class SoldierSkillUpResponse : global::ProtoBuf.IExtensible
  {
    public SoldierSkillUpResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierBattleListRequest")]
  public partial class SoldierBattleListRequest : global::ProtoBuf.IExtensible
  {
    public SoldierBattleListRequest() {}
    
    private int _battletype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"battletype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battletype
    {
      get { return _battletype; }
      set { _battletype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierBattleListResponse")]
  public partial class SoldierBattleListResponse : global::ProtoBuf.IExtensible
  {
    public SoldierBattleListResponse() {}
    
    private readonly global::System.Collections.Generic.List<int> _dsoldier_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"dsoldier_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> dsoldier_id
    {
      get { return _dsoldier_id; }
    }
  
    private int _captainid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"captainid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int captainid
    {
      get { return _captainid; }
      set { _captainid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}