//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: stage.proto
namespace stage
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageInfo")]
    public partial class StageInfo : global::ProtoBuf.IExtensible
    {
        public StageInfo() {}
        
        private int _action = (int)0;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue((int)0)]
        public int action {
            get { return _action; }
            set { _action = value; }
        }
        private int _id = (int) - 1;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue((int) - 1)]
        public int id {
            get { return _id; }
            set { _id = value; }
        }
        private int _uid = (int) - 1;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue((int) - 1)]
        public int uid {
            get { return _uid; }
            set { _uid = value; }
        }
        private int _counterpartid = (int) - 1;
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"counterpartid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue((int) - 1)]
        public int counterpartid {
            get { return _counterpartid; }
            set { _counterpartid = value; }
        }
        private int _star = (int) - 1;
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue((int) - 1)]
        public int star {
            get { return _star; }
            set { _star = value; }
        }
        private int _date = (int) - 1;
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"date", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue((int) - 1)]
        public int date {
            get { return _date; }
            set { _date = value; }
        }
        private int _times = (int) - 1;
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue((int) - 1)]
        public int times {
            get { return _times; }
            set { _times = value; }
        }
        private int _times_history = (int) - 1;
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"times_history", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue((int) - 1)]
        public int times_history {
            get { return _times_history; }
            set { _times_history = value; }
        }
        private int _times_reset = (int) - 1;
        [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"times_reset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue((int) - 1)]
        public int times_reset {
            get { return _times_reset; }
            set { _times_reset = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageInfoRequest")]
    public partial class StageInfoRequest : global::ProtoBuf.IExtensible
    {
        public StageInfoRequest() {}
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageInfoResponse")]
    public partial class StageInfoResponse : global::ProtoBuf.IExtensible
    {
        public StageInfoResponse() {}
        
        private readonly global::System.Collections.Generic.List<stage.StageInfo> _stage_infos = new global::System.Collections.Generic.List<stage.StageInfo>();
        [global::ProtoBuf.ProtoMember(1, Name = @"stage_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<stage.StageInfo> stage_infos {
            get { return _stage_infos; }
        }
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageAttackRequest")]
    public partial class StageAttackRequest : global::ProtoBuf.IExtensible
    {
        public StageAttackRequest() {}
        
        private int _stageid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"stageid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int stageid {
            get { return _stageid; }
            set { _stageid = value; }
        }
        private readonly global::System.Collections.Generic.List<int> _soldiers = new global::System.Collections.Generic.List<int>();
        [global::ProtoBuf.ProtoMember(2, Name = @"soldiers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public global::System.Collections.Generic.List<int> soldiers {
            get { return _soldiers; }
        }
        
        private int _captainid = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"captainid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int captainid {
            get { return _captainid; }
            set { _captainid = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageAttackResponse")]
    public partial class StageAttackResponse : global::ProtoBuf.IExtensible
    {
        public StageAttackResponse() {}
        
        private readonly global::System.Collections.Generic.List<stage.StageAttackResponse.RewardInfo> _rewards = new global::System.Collections.Generic.List<stage.StageAttackResponse.RewardInfo>();
        [global::ProtoBuf.ProtoMember(1, Name = @"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<stage.StageAttackResponse.RewardInfo> rewards {
            get { return _rewards; }
        }
        
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"RewardInfo")]
        public partial class RewardInfo : global::ProtoBuf.IExtensible
        {
            public RewardInfo() {}
            
            private int _monsterid;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"monsterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int monsterid {
                get { return _monsterid; }
                set { _monsterid = value; }
            }
            private readonly global::System.Collections.Generic.List<int> _drops = new global::System.Collections.Generic.List<int>();
            [global::ProtoBuf.ProtoMember(2, Name = @"drops", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public global::System.Collections.Generic.List<int> drops {
                get { return _drops; }
            }
            
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageSettleRequest")]
    public partial class StageSettleRequest : global::ProtoBuf.IExtensible
    {
        public StageSettleRequest() {}
        
        private int _stageid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"stageid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int stageid {
            get { return _stageid; }
            set { _stageid = value; }
        }
        private readonly global::System.Collections.Generic.List<int> _soldiers = new global::System.Collections.Generic.List<int>();
        [global::ProtoBuf.ProtoMember(2, Name = @"soldiers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public global::System.Collections.Generic.List<int> soldiers {
            get { return _soldiers; }
        }
        
        private readonly global::System.Collections.Generic.List<int> _builds = new global::System.Collections.Generic.List<int>();
        [global::ProtoBuf.ProtoMember(3, Name = @"builds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public global::System.Collections.Generic.List<int> builds {
            get { return _builds; }
        }
        
        private bool _active_exit = default(bool);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"active_exit", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool active_exit {
            get { return _active_exit; }
            set { _active_exit = value; }
        }
        private bool _timeout = default(bool);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"timeout", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool timeout {
            get { return _timeout; }
            set { _timeout = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageResource")]
    public partial class StageResource : global::ProtoBuf.IExtensible
    {
        public StageResource() {}
        
        private int _coin = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int coin {
            get { return _coin; }
            set { _coin = value; }
        }
        private int _wood = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"wood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int wood {
            get { return _wood; }
            set { _wood = value; }
        }
        private readonly global::System.Collections.Generic.List<stage.StageResource.ItemInfo> _rewards = new global::System.Collections.Generic.List<stage.StageResource.ItemInfo>();
        [global::ProtoBuf.ProtoMember(3, Name = @"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<stage.StageResource.ItemInfo> rewards {
            get { return _rewards; }
        }
        
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ItemInfo")]
        public partial class ItemInfo : global::ProtoBuf.IExtensible
        {
            public ItemInfo() {}
            
            private int _itemtypeid = default(int);
            [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"itemtypeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int itemtypeid {
                get { return _itemtypeid; }
                set { _itemtypeid = value; }
            }
            private int _superpose = (int)1;
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"superpose", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue((int)1)]
            public int superpose {
                get { return _superpose; }
                set { _superpose = value; }
            }
            private int _did = default(int);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"did", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int did {
                get { return _did; }
                set { _did = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageUserSettle")]
    public partial class StageUserSettle : global::ProtoBuf.IExtensible
    {
        public StageUserSettle() {}
        
        private int _exp = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int exp {
            get { return _exp; }
            set { _exp = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageSoldierSettle")]
    public partial class StageSoldierSettle : global::ProtoBuf.IExtensible
    {
        public StageSoldierSettle() {}
        
        private int _soldierid = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"soldierid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int soldierid {
            get { return _soldierid; }
            set { _soldierid = value; }
        }
        private int _exp = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int exp {
            get { return _exp; }
            set { _exp = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageSettleResponse")]
    public partial class StageSettleResponse : global::ProtoBuf.IExtensible
    {
        public StageSettleResponse() {}
        
        private stage.StageUserSettle _userinfo = null;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"userinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public stage.StageUserSettle userinfo {
            get { return _userinfo; }
            set { _userinfo = value; }
        }
        private readonly global::System.Collections.Generic.List<stage.StageSoldierSettle> _soldierinfos = new global::System.Collections.Generic.List<stage.StageSoldierSettle>();
        [global::ProtoBuf.ProtoMember(2, Name = @"soldierinfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<stage.StageSoldierSettle> soldierinfos {
            get { return _soldierinfos; }
        }
        
        private stage.StageResource _resource = null;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public stage.StageResource resource {
            get { return _resource; }
            set { _resource = value; }
        }
        private int _star = default(int);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int star {
            get { return _star; }
            set { _star = value; }
        }
        private bool _win = default(bool);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"win", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool win {
            get { return _win; }
            set { _win = value; }
        }
        private bool _gnomeshop = (bool)false;
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"gnomeshop", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue((bool)false)]
        public bool gnomeshop {
            get { return _gnomeshop; }
            set { _gnomeshop = value; }
        }
        private bool _blackshop = (bool)false;
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"blackshop", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue((bool)false)]
        public bool blackshop {
            get { return _blackshop; }
            set { _blackshop = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageScheduleRequest")]
    public partial class StageScheduleRequest : global::ProtoBuf.IExtensible
    {
        public StageScheduleRequest() {}
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageScheduleResponse")]
    public partial class StageScheduleResponse : global::ProtoBuf.IExtensible
    {
        public StageScheduleResponse() {}
        
        private int _normal;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"normal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int normal {
            get { return _normal; }
            set { _normal = value; }
        }
        private int _hard;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int hard {
            get { return _hard; }
            set { _hard = value; }
        }
        private int _team;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int team {
            get { return _team; }
            set { _team = value; }
        }
        private readonly global::System.Collections.Generic.List<stage.StageScheduleResponse.ScheduleInfo> _normal_info = new global::System.Collections.Generic.List<stage.StageScheduleResponse.ScheduleInfo>();
        [global::ProtoBuf.ProtoMember(4, Name = @"normal_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<stage.StageScheduleResponse.ScheduleInfo> normal_info {
            get { return _normal_info; }
        }
        
        private readonly global::System.Collections.Generic.List<stage.StageScheduleResponse.ScheduleInfo> _hard_info = new global::System.Collections.Generic.List<stage.StageScheduleResponse.ScheduleInfo>();
        [global::ProtoBuf.ProtoMember(5, Name = @"hard_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<stage.StageScheduleResponse.ScheduleInfo> hard_info {
            get { return _hard_info; }
        }
        
        private readonly global::System.Collections.Generic.List<stage.StageScheduleResponse.ScheduleInfo> _team_info = new global::System.Collections.Generic.List<stage.StageScheduleResponse.ScheduleInfo>();
        [global::ProtoBuf.ProtoMember(6, Name = @"team_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<stage.StageScheduleResponse.ScheduleInfo> team_info {
            get { return _team_info; }
        }
        
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ScheduleInfo")]
        public partial class ScheduleInfo : global::ProtoBuf.IExtensible
        {
            public ScheduleInfo() {}
            
            private int _star;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int star {
                get { return _star; }
                set { _star = value; }
            }
            private int _times;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int times {
                get { return _times; }
                set { _times = value; }
            }
            private int _stageid;
            [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"stageid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int stageid {
                get { return _stageid; }
                set { _stageid = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageRewardGetRequest")]
    public partial class StageRewardGetRequest : global::ProtoBuf.IExtensible
    {
        public StageRewardGetRequest() {}
        
        private int _stage_reward_id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"stage_reward_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int stage_reward_id {
            get { return _stage_reward_id; }
            set { _stage_reward_id = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageRewardGetResponse")]
    public partial class StageRewardGetResponse : global::ProtoBuf.IExtensible
    {
        public StageRewardGetResponse() {}
        
        private readonly global::System.Collections.Generic.List<stage.StageRewardGetResponse.ItemInfo> _itemlist = new global::System.Collections.Generic.List<stage.StageRewardGetResponse.ItemInfo>();
        [global::ProtoBuf.ProtoMember(1, Name = @"itemlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<stage.StageRewardGetResponse.ItemInfo> itemlist {
            get { return _itemlist; }
        }
        
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ItemInfo")]
        public partial class ItemInfo : global::ProtoBuf.IExtensible
        {
            public ItemInfo() {}
            
            private int _sitemtypeid;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"sitemtypeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int sitemtypeid {
                get { return _sitemtypeid; }
                set { _sitemtypeid = value; }
            }
            private int _did;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"did", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int did {
                get { return _did; }
                set { _did = value; }
            }
            private int _num = default(int);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int num {
                get { return _num; }
                set { _num = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageRewardFlagRequest")]
    public partial class StageRewardFlagRequest : global::ProtoBuf.IExtensible
    {
        public StageRewardFlagRequest() {}
        
        private readonly global::System.Collections.Generic.List<int> _stage_reward_ids = new global::System.Collections.Generic.List<int>();
        [global::ProtoBuf.ProtoMember(1, Name = @"stage_reward_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public global::System.Collections.Generic.List<int> stage_reward_ids {
            get { return _stage_reward_ids; }
        }
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageRewardFlagResponse")]
    public partial class StageRewardFlagResponse : global::ProtoBuf.IExtensible
    {
        public StageRewardFlagResponse() {}
        
        private readonly global::System.Collections.Generic.List<stage.StageRewardFlagResponse.StageRewardFlag> _flags = new global::System.Collections.Generic.List<stage.StageRewardFlagResponse.StageRewardFlag>();
        [global::ProtoBuf.ProtoMember(1, Name = @"flags", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<stage.StageRewardFlagResponse.StageRewardFlag> flags {
            get { return _flags; }
        }
        
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageRewardFlag")]
        public partial class StageRewardFlag : global::ProtoBuf.IExtensible
        {
            public StageRewardFlag() {}
            
            private int _stage_reward_id;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"stage_reward_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int stage_reward_id {
                get { return _stage_reward_id; }
                set { _stage_reward_id = value; }
            }
            private int _flag;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int flag {
                get { return _flag; }
                set { _flag = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageResetRequest")]
    public partial class StageResetRequest : global::ProtoBuf.IExtensible
    {
        public StageResetRequest() {}
        
        private int _stageid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"stageid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int stageid {
            get { return _stageid; }
            set { _stageid = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageResetResponse")]
    public partial class StageResetResponse : global::ProtoBuf.IExtensible
    {
        public StageResetResponse() {}
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageGetScriptDropRequest")]
    public partial class StageGetScriptDropRequest : global::ProtoBuf.IExtensible
    {
        public StageGetScriptDropRequest() {}
        
        private int _stageid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"stageid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int stageid {
            get { return _stageid; }
            set { _stageid = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageGetScriptDropResponse")]
    public partial class StageGetScriptDropResponse : global::ProtoBuf.IExtensible
    {
        public StageGetScriptDropResponse() {}
        
        private readonly global::System.Collections.Generic.List<stage.StageGetScriptDropResponse.dropinfo> _infos = new global::System.Collections.Generic.List<stage.StageGetScriptDropResponse.dropinfo>();
        [global::ProtoBuf.ProtoMember(1, Name = @"infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<stage.StageGetScriptDropResponse.dropinfo> infos {
            get { return _infos; }
        }
        
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"dropinfo")]
        public partial class dropinfo : global::ProtoBuf.IExtensible
        {
            public dropinfo() {}
            
            private int _type;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int type {
                get { return _type; }
                set { _type = value; }
            }
            private int _value;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int value {
                get { return _value; }
                set { _value = value; }
            }
            private int _num = default(int);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int num {
                get { return _num; }
                set { _num = value; }
            }
            private bool _issoul = default(bool);
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"issoul", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(default(bool))]
            public bool issoul {
                get { return _issoul; }
                set { _issoul = value; }
            }
            private bool _isbook = default(bool);
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"isbook", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(default(bool))]
            public bool isbook {
                get { return _isbook; }
                set { _isbook = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageSweepRequest")]
    public partial class StageSweepRequest : global::ProtoBuf.IExtensible
    {
        public StageSweepRequest() {}
        
        private int _stageid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"stageid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int stageid {
            get { return _stageid; }
            set { _stageid = value; }
        }
        private int _times;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int times {
            get { return _times; }
            set { _times = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageSweepResponse")]
    public partial class StageSweepResponse : global::ProtoBuf.IExtensible
    {
        public StageSweepResponse() {}
        
        private readonly global::System.Collections.Generic.List<stage.StageSweepResponse.StageSweepReward> _sweep_reward = new global::System.Collections.Generic.List<stage.StageSweepResponse.StageSweepReward>();
        [global::ProtoBuf.ProtoMember(1, Name = @"sweep_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<stage.StageSweepResponse.StageSweepReward> sweep_reward {
            get { return _sweep_reward; }
        }
        
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StageSweepReward")]
        public partial class StageSweepReward : global::ProtoBuf.IExtensible
        {
            public StageSweepReward() {}
            
            private stage.StageUserSettle _userinfo = null;
            [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"userinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public stage.StageUserSettle userinfo {
                get { return _userinfo; }
                set { _userinfo = value; }
            }
            private readonly global::System.Collections.Generic.List<stage.StageSoldierSettle> _soldierinfos = new global::System.Collections.Generic.List<stage.StageSoldierSettle>();
            [global::ProtoBuf.ProtoMember(2, Name = @"soldierinfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<stage.StageSoldierSettle> soldierinfos {
                get { return _soldierinfos; }
            }
            
            private stage.StageResource _resource = null;
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public stage.StageResource resource {
                get { return _resource; }
                set { _resource = value; }
            }
            private readonly global::System.Collections.Generic.List<stage.StageSweepResponse.StageSweepReward.SweepExtraReward> _extra_reward = new global::System.Collections.Generic.List<stage.StageSweepResponse.StageSweepReward.SweepExtraReward>();
            [global::ProtoBuf.ProtoMember(4, Name = @"extra_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<stage.StageSweepResponse.StageSweepReward.SweepExtraReward> extra_reward {
                get { return _extra_reward; }
            }
            
            private bool _gnomeshop = (bool)false;
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"gnomeshop", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue((bool)false)]
            public bool gnomeshop {
                get { return _gnomeshop; }
                set { _gnomeshop = value; }
            }
            private bool _blackshop = (bool)false;
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"blackshop", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue((bool)false)]
            public bool blackshop {
                get { return _blackshop; }
                set { _blackshop = value; }
            }
            [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SweepExtraReward")]
            public partial class SweepExtraReward : global::ProtoBuf.IExtensible
            {
                public SweepExtraReward() {}
                
                private int _itemid = default(int);
                [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
                [global::System.ComponentModel.DefaultValue(default(int))]
                public int itemid {
                    get { return _itemid; }
                    set { _itemid = value; }
                }
                private int _number = default(int);
                [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
                [global::System.ComponentModel.DefaultValue(default(int))]
                public int number {
                    get { return _number; }
                    set { _number = value; }
                }
                private global::ProtoBuf.IExtension extensionObject;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                {
                    return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
                }
            }
            
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }
    
}