//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: system.proto
namespace system
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShutDown")]
  public partial class ShutDown : global::ProtoBuf.IExtensible
  {
    public ShutDown() {}
    
    private int _left_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"left_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int left_time
    {
      get { return _left_time; }
      set { _left_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}