//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: tga.proto
namespace tga
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierBornRequest")]
  public partial class SoldierBornRequest : global::ProtoBuf.IExtensible
  {
    public SoldierBornRequest() {}
    
    private tga.tgaTime _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.tgaTime time
    {
      get { return _time; }
      set { _time = value; }
    }
    private tga.lifestateinfo _info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.lifestateinfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierBornResponse")]
  public partial class SoldierBornResponse : global::ProtoBuf.IExtensible
  {
    public SoldierBornResponse() {}
    
    private tga.tgaTime _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.tgaTime time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierDeadRequest")]
  public partial class SoldierDeadRequest : global::ProtoBuf.IExtensible
  {
    public SoldierDeadRequest() {}
    
    private tga.tgaTime _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.tgaTime time
    {
      get { return _time; }
      set { _time = value; }
    }
    private tga.lifestateinfo _info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.lifestateinfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierDeadResponse")]
  public partial class SoldierDeadResponse : global::ProtoBuf.IExtensible
  {
    public SoldierDeadResponse() {}
    
    private tga.tgaTime _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.tgaTime time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierRunRoadRequest")]
  public partial class SoldierRunRoadRequest : global::ProtoBuf.IExtensible
  {
    public SoldierRunRoadRequest() {}
    
    private tga.tgaTime _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.tgaTime time
    {
      get { return _time; }
      set { _time = value; }
    }
    private tga.lifestateinfo _info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.lifestateinfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private tga.GridPos _start;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.GridPos start
    {
      get { return _start; }
      set { _start = value; }
    }
    private tga.GridPos _end;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.GridPos end
    {
      get { return _end; }
      set { _end = value; }
    }
    private readonly global::System.Collections.Generic.List<tga.pathroad> _roadlist = new global::System.Collections.Generic.List<tga.pathroad>();
    [global::ProtoBuf.ProtoMember(5, Name=@"roadlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tga.pathroad> roadlist
    {
      get { return _roadlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierRunRoadResponse")]
  public partial class SoldierRunRoadResponse : global::ProtoBuf.IExtensible
  {
    public SoldierRunRoadResponse() {}
    
    private tga.tgaTime _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.tgaTime time
    {
      get { return _time; }
      set { _time = value; }
    }
    private tga.GridPos _start;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.GridPos start
    {
      get { return _start; }
      set { _start = value; }
    }
    private tga.GridPos _end;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.GridPos end
    {
      get { return _end; }
      set { _end = value; }
    }
    private readonly global::System.Collections.Generic.List<tga.pathroad> _roadlist = new global::System.Collections.Generic.List<tga.pathroad>();
    [global::ProtoBuf.ProtoMember(4, Name=@"roadlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tga.pathroad> roadlist
    {
      get { return _roadlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierSkillAttackRequest")]
  public partial class SoldierSkillAttackRequest : global::ProtoBuf.IExtensible
  {
    public SoldierSkillAttackRequest() {}
    
    private tga.tgaTime _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.tgaTime time
    {
      get { return _time; }
      set { _time = value; }
    }
    private tga.lifestateinfo _info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.lifestateinfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private int _skillid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _SkillObjlist = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"SkillObjlist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> SkillObjlist
    {
      get { return _SkillObjlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierSkillAttackResponse")]
  public partial class SoldierSkillAttackResponse : global::ProtoBuf.IExtensible
  {
    public SoldierSkillAttackResponse() {}
    
    private tga.tgaTime _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.tgaTime time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _skillid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _SkillObjlist = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"SkillObjlist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> SkillObjlist
    {
      get { return _SkillObjlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pathroad")]
  public partial class pathroad : global::ProtoBuf.IExtensible
  {
    public pathroad() {}
    
    private tga.GridPos _road;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"road", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public tga.GridPos road
    {
      get { return _road; }
      set { _road = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _deltaTime = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deltaTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int deltaTime
    {
      get { return _deltaTime; }
      set { _deltaTime = value; }
    }
    private int _dir = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private int _gs = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gs
    {
      get { return _gs; }
      set { _gs = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GridPos")]
  public partial class GridPos : global::ProtoBuf.IExtensible
  {
    public GridPos() {}
    
    private int _unit;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unit
    {
      get { return _unit; }
      set { _unit = value; }
    }
    private int _layer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"layer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int layer
    {
      get { return _layer; }
      set { _layer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"tgaTime")]
  public partial class tgaTime : global::ProtoBuf.IExtensible
  {
    public tgaTime() {}
    
    private float _Requesttime = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Requesttime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float Requesttime
    {
      get { return _Requesttime; }
      set { _Requesttime = value; }
    }
    private float _servertime = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"servertime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float servertime
    {
      get { return _servertime; }
      set { _servertime = value; }
    }
    private float _Responsetime = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Responsetime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float Responsetime
    {
      get { return _Responsetime; }
      set { _Responsetime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"lifestateinfo")]
  public partial class lifestateinfo : global::ProtoBuf.IExtensible
  {
    public lifestateinfo() {}
    
    private int _hp = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private tga.GridPos _CurPos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CurPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tga.GridPos CurPos
    {
      get { return _CurPos; }
      set { _CurPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}