//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: treasure.proto
// Note: requires additional types generated from: battle.proto
namespace treasure
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureObjInfo")]
  public partial class TreasureObjInfo : global::ProtoBuf.IExtensible
  {
    public TreasureObjInfo() {}
    
    private int _objid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"objid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int objid
    {
      get { return _objid; }
      set { _objid = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _hp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _mp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mp
    {
      get { return _mp; }
      set { _mp = value; }
    }
    private int _cx = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cx
    {
      get { return _cx; }
      set { _cx = value; }
    }
    private int _cy = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cy
    {
      get { return _cy; }
      set { _cy = value; }
    }
    private int _quality = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _starlevel = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"starlevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int starlevel
    {
      get { return _starlevel; }
      set { _starlevel = value; }
    }
    private int _soldiertypeid = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"soldiertypeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int soldiertypeid
    {
      get { return _soldiertypeid; }
      set { _soldiertypeid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureSearchRequest")]
  public partial class TreasureSearchRequest : global::ProtoBuf.IExtensible
  {
    public TreasureSearchRequest() {}
    
    private bool _pull_all;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pull_all", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool pull_all
    {
      get { return _pull_all; }
      set { _pull_all = value; }
    }
    private int _pirate_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pirate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pirate_id
    {
      get { return _pirate_id; }
      set { _pirate_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureSearchInfo")]
  public partial class TreasureSearchInfo : global::ProtoBuf.IExtensible
  {
    public TreasureSearchInfo() {}
    
    private int _pirate_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pirate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pirate_id
    {
      get { return _pirate_id; }
      set { _pirate_id = value; }
    }
    private battle.DefInfoResponse _definfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"definfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public battle.DefInfoResponse definfo
    {
      get { return _definfo; }
      set { _definfo = value; }
    }
    private int _surplus_coin = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"surplus_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int surplus_coin
    {
      get { return _surplus_coin; }
      set { _surplus_coin = value; }
    }
    private int _surplus_diamond = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"surplus_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int surplus_diamond
    {
      get { return _surplus_diamond; }
      set { _surplus_diamond = value; }
    }
    private readonly global::System.Collections.Generic.List<treasure.TreasureObjInfo> _def_status = new global::System.Collections.Generic.List<treasure.TreasureObjInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"def_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureObjInfo> def_status
    {
      get { return _def_status; }
    }
  
    private int _end_time = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private int _rob_count = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rob_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rob_count
    {
      get { return _rob_count; }
      set { _rob_count = value; }
    }
    private readonly global::System.Collections.Generic.List<treasure.TreasureObjInfo> _self_status = new global::System.Collections.Generic.List<treasure.TreasureObjInfo>();
    [global::ProtoBuf.ProtoMember(8, Name=@"self_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureObjInfo> self_status
    {
      get { return _self_status; }
    }
  
    private int _power = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }
    private int _origin = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"origin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int origin
    {
      get { return _origin; }
      set { _origin = value; }
    }
    private int _avenge = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"avenge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int avenge
    {
      get { return _avenge; }
      set { _avenge = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureSearchResponse")]
  public partial class TreasureSearchResponse : global::ProtoBuf.IExtensible
  {
    public TreasureSearchResponse() {}
    
    private readonly global::System.Collections.Generic.List<treasure.TreasureSearchInfo> _treasure_infos = new global::System.Collections.Generic.List<treasure.TreasureSearchInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"treasure_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureSearchInfo> treasure_infos
    {
      get { return _treasure_infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureOriginInfo")]
  public partial class TreasureOriginInfo : global::ProtoBuf.IExtensible
  {
    public TreasureOriginInfo() {}
    
    private int _pirate_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pirate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pirate_id
    {
      get { return _pirate_id; }
      set { _pirate_id = value; }
    }
    private int _origin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"origin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int origin
    {
      get { return _origin; }
      set { _origin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureSetOriginRequest")]
  public partial class TreasureSetOriginRequest : global::ProtoBuf.IExtensible
  {
    public TreasureSetOriginRequest() {}
    
    private readonly global::System.Collections.Generic.List<treasure.TreasureOriginInfo> _info = new global::System.Collections.Generic.List<treasure.TreasureOriginInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureOriginInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureSetOriginResponse")]
  public partial class TreasureSetOriginResponse : global::ProtoBuf.IExtensible
  {
    public TreasureSetOriginResponse() {}
    
    private readonly global::System.Collections.Generic.List<treasure.TreasureOriginInfo> _info = new global::System.Collections.Generic.List<treasure.TreasureOriginInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureOriginInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureRobRequest")]
  public partial class TreasureRobRequest : global::ProtoBuf.IExtensible
  {
    public TreasureRobRequest() {}
    
    private string _servernode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"servernode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string servernode
    {
      get { return _servernode; }
      set { _servernode = value; }
    }
    private int _belong_uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"belong_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int belong_uid
    {
      get { return _belong_uid; }
      set { _belong_uid = value; }
    }
    private int _pirate_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pirate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pirate_id
    {
      get { return _pirate_id; }
      set { _pirate_id = value; }
    }
    private int _canvas_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"canvas_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int canvas_id
    {
      get { return _canvas_id; }
      set { _canvas_id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _soldiers = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"soldiers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> soldiers
    {
      get { return _soldiers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureRobResponse")]
  public partial class TreasureRobResponse : global::ProtoBuf.IExtensible
  {
    public TreasureRobResponse() {}
    
    private string _servernode = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"servernode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string servernode
    {
      get { return _servernode; }
      set { _servernode = value; }
    }
    private int _belong_uid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"belong_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int belong_uid
    {
      get { return _belong_uid; }
      set { _belong_uid = value; }
    }
    private int _pirate_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pirate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pirate_id
    {
      get { return _pirate_id; }
      set { _pirate_id = value; }
    }
    private battle.DefInfoResponse _definfo = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"definfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public battle.DefInfoResponse definfo
    {
      get { return _definfo; }
      set { _definfo = value; }
    }
    private readonly global::System.Collections.Generic.List<treasure.TreasureObjInfo> _status = new global::System.Collections.Generic.List<treasure.TreasureObjInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureObjInfo> status
    {
      get { return _status; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureExitRobRequest")]
  public partial class TreasureExitRobRequest : global::ProtoBuf.IExtensible
  {
    public TreasureExitRobRequest() {}
    
    private int _pirateid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pirateid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pirateid
    {
      get { return _pirateid; }
      set { _pirateid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureExitRobResponse")]
  public partial class TreasureExitRobResponse : global::ProtoBuf.IExtensible
  {
    public TreasureExitRobResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureRobSettleRequest")]
  public partial class TreasureRobSettleRequest : global::ProtoBuf.IExtensible
  {
    public TreasureRobSettleRequest() {}
    
    private readonly global::System.Collections.Generic.List<treasure.TreasureRobSettleRequest.TrapInfo> _trap_infos = new global::System.Collections.Generic.List<treasure.TreasureRobSettleRequest.TrapInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"trap_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureRobSettleRequest.TrapInfo> trap_infos
    {
      get { return _trap_infos; }
    }
  
    private readonly global::System.Collections.Generic.List<treasure.TreasureRobSettleRequest.SoldierInfo> _def_soldier_infos = new global::System.Collections.Generic.List<treasure.TreasureRobSettleRequest.SoldierInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"def_soldier_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureRobSettleRequest.SoldierInfo> def_soldier_infos
    {
      get { return _def_soldier_infos; }
    }
  
    private readonly global::System.Collections.Generic.List<treasure.TreasureRobSettleRequest.SoldierInfo> _attack_soldier_infos = new global::System.Collections.Generic.List<treasure.TreasureRobSettleRequest.SoldierInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attack_soldier_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureRobSettleRequest.SoldierInfo> attack_soldier_infos
    {
      get { return _attack_soldier_infos; }
    }
  
    private int _pirate_id = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pirate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pirate_id
    {
      get { return _pirate_id; }
      set { _pirate_id = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrapInfo")]
  public partial class TrapInfo : global::ProtoBuf.IExtensible
  {
    public TrapInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _cx;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cx
    {
      get { return _cx; }
      set { _cx = value; }
    }
    private int _cy;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cy
    {
      get { return _cy; }
      set { _cy = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _mp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mp
    {
      get { return _mp; }
      set { _mp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierInfo")]
  public partial class SoldierInfo : global::ProtoBuf.IExtensible
  {
    public SoldierInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _cx;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cx
    {
      get { return _cx; }
      set { _cx = value; }
    }
    private int _cy;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cy
    {
      get { return _cy; }
      set { _cy = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _mp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mp
    {
      get { return _mp; }
      set { _mp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureRobSettleResponse")]
  public partial class TreasureRobSettleResponse : global::ProtoBuf.IExtensible
  {
    public TreasureRobSettleResponse() {}
    
    private int _pirate_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pirate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pirate_id
    {
      get { return _pirate_id; }
      set { _pirate_id = value; }
    }
    private bool _win = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool win
    {
      get { return _win; }
      set { _win = value; }
    }
    private int _coin = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private battle.SettleResponse _pvpinfo = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pvpinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public battle.SettleResponse pvpinfo
    {
      get { return _pvpinfo; }
      set { _pvpinfo = value; }
    }
    private bool _gnomeshop = (bool)false;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gnomeshop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool gnomeshop
    {
      get { return _gnomeshop; }
      set { _gnomeshop = value; }
    }
    private bool _blackshop = (bool)false;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"blackshop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool blackshop
    {
      get { return _blackshop; }
      set { _blackshop = value; }
    }
    private int _shipdrawingid = (int)-1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"shipdrawingid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int shipdrawingid
    {
      get { return _shipdrawingid; }
      set { _shipdrawingid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureExploitRequest")]
  public partial class TreasureExploitRequest : global::ProtoBuf.IExtensible
  {
    public TreasureExploitRequest() {}
    
    private int _treasureid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"treasureid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int treasureid
    {
      get { return _treasureid; }
      set { _treasureid = value; }
    }
    private int _canvasid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"canvasid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int canvasid
    {
      get { return _canvasid; }
      set { _canvasid = value; }
    }
    private int _scale = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureExploitResponse")]
  public partial class TreasureExploitResponse : global::ProtoBuf.IExtensible
  {
    public TreasureExploitResponse() {}
    
    private int _treasureid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"treasureid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int treasureid
    {
      get { return _treasureid; }
      set { _treasureid = value; }
    }
    private int _endtime = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int endtime
    {
      get { return _endtime; }
      set { _endtime = value; }
    }
    private int _profit_coin = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"profit_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profit_coin
    {
      get { return _profit_coin; }
      set { _profit_coin = value; }
    }
    private int _profit_diamond = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"profit_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profit_diamond
    {
      get { return _profit_diamond; }
      set { _profit_diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureInfoRequest")]
  public partial class TreasureInfoRequest : global::ProtoBuf.IExtensible
  {
    public TreasureInfoRequest() {}
    
    private readonly global::System.Collections.Generic.List<int> _treasureids = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"treasureids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> treasureids
    {
      get { return _treasureids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureInfoResponse")]
  public partial class TreasureInfoResponse : global::ProtoBuf.IExtensible
  {
    public TreasureInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<treasure.TreasureInfoResponse.TreasureInfo> _treasure_info = new global::System.Collections.Generic.List<treasure.TreasureInfoResponse.TreasureInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"treasure_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureInfoResponse.TreasureInfo> treasure_info
    {
      get { return _treasure_info; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureInfo")]
  public partial class TreasureInfo : global::ProtoBuf.IExtensible
  {
    public TreasureInfo() {}
    
    private int _treasure_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"treasure_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int treasure_id
    {
      get { return _treasure_id; }
      set { _treasure_id = value; }
    }
    private int _canvas_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"canvas_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int canvas_id
    {
      get { return _canvas_id; }
      set { _canvas_id = value; }
    }
    private int _scale = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private int _endtime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int endtime
    {
      get { return _endtime; }
      set { _endtime = value; }
    }
    private int _rob_coin = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rob_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rob_coin
    {
      get { return _rob_coin; }
      set { _rob_coin = value; }
    }
    private int _rob_diamond = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"rob_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rob_diamond
    {
      get { return _rob_diamond; }
      set { _rob_diamond = value; }
    }
    private int _profit_coin = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"profit_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profit_coin
    {
      get { return _profit_coin; }
      set { _profit_coin = value; }
    }
    private int _profit_diamond = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"profit_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profit_diamond
    {
      get { return _profit_diamond; }
      set { _profit_diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureHarvestRequest")]
  public partial class TreasureHarvestRequest : global::ProtoBuf.IExtensible
  {
    public TreasureHarvestRequest() {}
    
    private int _treasureid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"treasureid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int treasureid
    {
      get { return _treasureid; }
      set { _treasureid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureHarvestResponse")]
  public partial class TreasureHarvestResponse : global::ProtoBuf.IExtensible
  {
    public TreasureHarvestResponse() {}
    
    private int _treasureid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"treasureid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int treasureid
    {
      get { return _treasureid; }
      set { _treasureid = value; }
    }
    private int _coin = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _rob_coin = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rob_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rob_coin
    {
      get { return _rob_coin; }
      set { _rob_coin = value; }
    }
    private int _rob_diamond = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rob_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rob_diamond
    {
      get { return _rob_diamond; }
      set { _rob_diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureBattleListRequest")]
  public partial class TreasureBattleListRequest : global::ProtoBuf.IExtensible
  {
    public TreasureBattleListRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureBattleListResponse")]
  public partial class TreasureBattleListResponse : global::ProtoBuf.IExtensible
  {
    public TreasureBattleListResponse() {}
    
    private readonly global::System.Collections.Generic.List<treasure.TreasureBattleListResponse.BattleListInfo> _battlelistinfo = new global::System.Collections.Generic.List<treasure.TreasureBattleListResponse.BattleListInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"battlelistinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureBattleListResponse.BattleListInfo> battlelistinfo
    {
      get { return _battlelistinfo; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleListInfo")]
  public partial class BattleListInfo : global::ProtoBuf.IExtensible
  {
    public BattleListInfo() {}
    
    private string _battleindex = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"battleindex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string battleindex
    {
      get { return _battleindex; }
      set { _battleindex = value; }
    }
    private int _win = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int win
    {
      get { return _win; }
      set { _win = value; }
    }
    private string _level = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _servername = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"servername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string servername
    {
      get { return _servername; }
      set { _servername = value; }
    }
    private int _rob_time = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"rob_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rob_time
    {
      get { return _rob_time; }
      set { _rob_time = value; }
    }
    private int _rob_coin = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rob_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rob_coin
    {
      get { return _rob_coin; }
      set { _rob_coin = value; }
    }
    private int _rob_diamond = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"rob_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rob_diamond
    {
      get { return _rob_diamond; }
      set { _rob_diamond = value; }
    }
    private int _flag = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private int _avenge = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"avenge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int avenge
    {
      get { return _avenge; }
      set { _avenge = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureBattleReportDetailRequest")]
  public partial class TreasureBattleReportDetailRequest : global::ProtoBuf.IExtensible
  {
    public TreasureBattleReportDetailRequest() {}
    
    private string _battleindex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"battleindex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string battleindex
    {
      get { return _battleindex; }
      set { _battleindex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureBattleReportDetailResponse")]
  public partial class TreasureBattleReportDetailResponse : global::ProtoBuf.IExtensible
  {
    public TreasureBattleReportDetailResponse() {}
    
    private readonly global::System.Collections.Generic.List<treasure.TreasureBattleReportDetailResponse.ReportDetail> _details = new global::System.Collections.Generic.List<treasure.TreasureBattleReportDetailResponse.ReportDetail>();
    [global::ProtoBuf.ProtoMember(1, Name=@"details", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureBattleReportDetailResponse.ReportDetail> details
    {
      get { return _details; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReportDetail")]
  public partial class ReportDetail : global::ProtoBuf.IExtensible
  {
    public ReportDetail() {}
    
    private string _battleindex = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"battleindex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string battleindex
    {
      get { return _battleindex; }
      set { _battleindex = value; }
    }
    private int _report_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"report_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int report_id
    {
      get { return _report_id; }
      set { _report_id = value; }
    }
    private battle.DefInfoResponse _definfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"definfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public battle.DefInfoResponse definfo
    {
      get { return _definfo; }
      set { _definfo = value; }
    }
    private readonly global::System.Collections.Generic.List<treasure.TreasureObjInfo> _defstatus = new global::System.Collections.Generic.List<treasure.TreasureObjInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"defstatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureObjInfo> defstatus
    {
      get { return _defstatus; }
    }
  
    private readonly global::System.Collections.Generic.List<treasure.TreasureObjInfo> _robinfo = new global::System.Collections.Generic.List<treasure.TreasureObjInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"robinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<treasure.TreasureObjInfo> robinfo
    {
      get { return _robinfo; }
    }
  
    private string _level = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _servername = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"servername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string servername
    {
      get { return _servername; }
      set { _servername = value; }
    }
    private int _win = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int win
    {
      get { return _win; }
      set { _win = value; }
    }
    private int _power = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureBattleReportReadRequest")]
  public partial class TreasureBattleReportReadRequest : global::ProtoBuf.IExtensible
  {
    public TreasureBattleReportReadRequest() {}
    
    private bool _isavenge = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isavenge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isavenge
    {
      get { return _isavenge; }
      set { _isavenge = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureBattleReportReadResponse")]
  public partial class TreasureBattleReportReadResponse : global::ProtoBuf.IExtensible
  {
    public TreasureBattleReportReadResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureAvengeRequest")]
  public partial class TreasureAvengeRequest : global::ProtoBuf.IExtensible
  {
    public TreasureAvengeRequest() {}
    
    private string _battleindex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"battleindex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string battleindex
    {
      get { return _battleindex; }
      set { _battleindex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureAvengeResponse")]
  public partial class TreasureAvengeResponse : global::ProtoBuf.IExtensible
  {
    public TreasureAvengeResponse() {}
    
    private treasure.TreasureSearchInfo _pirate_info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pirate_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public treasure.TreasureSearchInfo pirate_info
    {
      get { return _pirate_info; }
      set { _pirate_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}